---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 백업 리소스 그룹을 생성, 수정, 삭제할 수 있으며, 리소스 그룹에 대한 백업 작업을 수행할 수 있습니다. 
---
= 리소스 그룹 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
백업 리소스 그룹을 생성, 수정, 삭제할 수 있으며, 리소스 그룹에 대한 백업 작업을 수행할 수 있습니다.


NOTE: 리소스 그룹은 VSC(Virtual Storage Console)에서 백업 작업이라고 합니다.



[[suspend-and-resume-operations-on-resource-groups]]
== 리소스 그룹에서 작업 일시 중단 및 재개

리소스 그룹에서 예약된 작업이 시작되지 않도록 일시적으로 비활성화할 수 있습니다. 나중에 원할 때 해당 작업을 활성화할 수 있습니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *리소스 그룹*을 선택하고, 리소스 그룹을 선택한 후 *일시 중단*(또는 *다시 시작*)을 선택합니다.
. 확인 상자에서 *확인*을 선택하여 확인합니다.


.당신이 완료한 후
리소스 그룹 페이지에서 일시 중단된 리소스의 작업 상태는 다음과 같습니다. `Under_Maintenance` .  작업 상태 열을 보려면 표 오른쪽으로 스크롤해야 할 수도 있습니다.

백업 작업이 재개되면 작업 상태가 다음으로 변경됩니다. `Production` .



[[modify-resource-groups]]
== 리소스 그룹 수정

vCenter의 리소스 그룹에서 리소스를 제거하거나 추가하고, 정책을 분리하거나 연결하고, 일정을 수정하거나 다른 리소스 그룹 옵션을 수정할 수 있습니다.

.이 작업에 관하여
리소스 그룹의 이름을 수정하려면 VM, 데이터 저장소, 정책, 백업 또는 리소스 그룹 이름에 다음 특수 문자를 사용하지 마세요.

% & * $ # @ ! \ / : * ? " < > - | ; ' , 그리고 공백. 밑줄 문자(_)가 허용됩니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *리소스 그룹*을 선택한 다음, 리소스 그룹을 선택하고 *편집*을 선택합니다.
. *리소스 그룹 편집* 마법사의 왼쪽 목록에서 수정하려는 범주를 선택하고 변경 사항을 입력합니다.
+
여러 카테고리에서 변경을 할 수 있습니다.  이 옵션에서는 2차적으로 보호된 리소스도 편집할 수 있습니다.

. 요약 페이지가 나올 때까지 *다음*을 선택한 다음, *마침*을 선택합니다.




[[delete-resource-groups]]
== 리소스 그룹 삭제

더 이상 리소스 그룹의 리소스를 보호할 필요가 없으면 vCenter에서 리소스 그룹을 삭제할 수 있습니다.  vCenter에서 SnapCenter Plug-in for VMware vSphere 제거하기 전에 모든 리소스 그룹이 삭제되었는지 확인해야 합니다.

.이 작업에 관하여
모든 리소스 그룹 삭제 작업은 강제 삭제로 수행됩니다. 삭제 작업은 vCenter 리소스 그룹에서 모든 정책을 분리하고, SnapCenter Plug-in for VMware vSphere 에서 리소스 그룹을 제거하고, 리소스 그룹의 모든 백업과 스냅샷을 삭제합니다.


NOTE: SnapVault 관계에서는 마지막 스냅샷을 삭제할 수 없으므로 리소스 그룹을 삭제할 수 없습니다.  SnapVault 관계에 속한 리소스 그룹을 삭제하기 전에 System Manager나 ONTAP CLI를 사용하여 SnapVault 관계를 제거한 다음 마지막 스냅샷을 삭제해야 합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *리소스 그룹*을 선택한 다음, 리소스 그룹을 선택하고 *삭제*를 선택합니다.
. *리소스 그룹 삭제* 확인 상자에서 *확인*을 선택하여 확인합니다.

