---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= SnapCenter Plug-in for VMware vSphere 배포
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
가상화된 머신에서 VM, 데이터 저장소 및 애플리케이션 일관성 데이터베이스를 보호하기 위해 SnapCenter 기능을 사용하려면 SnapCenter Plug-in for VMware vSphere 배포해야 합니다.  그만큼link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance(OVA) 다운로드"^] 이 페이지에서는 OVA 파일을 다운로드하는 방법에 대한 지침을 제공합니다.

. VMware vCenter 7.0.3 이상 버전의 경우 다음 단계를 따르세요.link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance(OVA) 다운로드"^] 인증서를 vCenter로 가져옵니다.
. 브라우저에서 VMware vSphere vCenter로 이동합니다.
+

NOTE: IPv6 주소 HTML 웹 클라이언트의 경우 Chrome이나 Firefox를 사용해야 합니다.

. *VMware vCenter Single Sign-On 페이지*에 로그인합니다.
. 탐색 창에서 데이터 센터, 폴더, 클러스터 또는 호스트와 같은 가상 머신의 유효한 상위 개체인 인벤토리 개체를 마우스 오른쪽 버튼으로 클릭하고 *OVF 템플릿 배포*를 선택하여 VMware 배포 마법사를 시작합니다.
. *OVF 템플릿 선택* 페이지에서 위치를 지정하세요. `.ova` 파일(아래 표 참조)을 선택하고 *다음*을 선택합니다.
+
|===
| 이 마법사 페이지에서는… | 이렇게 하세요… 


| 이름과 폴더를 선택하세요 | VM 또는 vApp에 대한 고유한 이름을 입력하고 배포 위치를 선택합니다. 


| 리소스를 선택하세요 | 배포된 VM 템플릿을 실행할 리소스를 선택합니다. 


| 리뷰 세부 정보 | 확인하다 `.ova` 템플릿 세부정보. 


| 라이센스 계약 | *모든 라이선스 계약에 동의합니다* 확인란을 선택하세요. 


| 저장소 선택 | 배포된 OVF 템플릿의 파일을 어디에 어떻게 저장할지 정의합니다. 


| 네트워크 선택 | 소스 네트워크를 선택하고 대상 네트워크에 매핑합니다. 


| 템플릿 사용자 정의  a| 
*기존 vCenter에 등록*에서 vCenter 자격 증명을 입력합니다.  * SnapCenter Plug-in for VMware vSphere 만들기*에서 SnapCenter Plug-in for VMware vSphere 입력합니다.


NOTE: 지정한 사용자 이름과 비밀번호를 기록해 두세요.  나중에 VMware vSphere용 SnapCenter 플러그인 구성을 수정하려면 이러한 자격 증명을 사용해야 합니다.

*네트워크 속성 설정* 섹션에서 네트워크 정보를 입력합니다.  *설정 날짜 및 시간* 섹션에서 vCenter가 있는 시간대를 선택합니다.



| 완료 준비 완료 | 페이지를 검토하고 *마침*을 선택하세요. 
|===
+

NOTE: 모든 호스트는 IP 주소로 구성되어야 합니다(FQDN 호스트 이름은 지원되지 않음).  배포 작업은 배포 전에 입력 내용의 유효성을 검사하지 않습니다.

. SnapCenter Plug-in for VMware vSphere 배포된 VM으로 이동한 다음, *요약* 탭을 선택하고, *전원 켜기* 상자를 선택하여 SnapCenter Plug-in for VMware vSphere 시작합니다.
. SnapCenter Plug-in for VMware vSphere 켜지는 동안 배포된 SnapCenter Plug-in for VMware vSphere 마우스 오른쪽 버튼으로 클릭하고 *게스트 OS*를 선택한 다음 *VMware 도구 설치*를 선택합니다.
+
배포가 완료되기까지 몇 분이 걸릴 수 있습니다.  SnapCenter Plug-in for VMware vSphere 전원이 켜지고, VMware 도구가 설치되고, SnapCenter Plug-in for VMware vSphere 에 로그인하라는 메시지가 화면에 표시되면 배포가 성공적으로 완료된 것입니다.

+
화면에는 SnapCenter Plug-in for VMware vSphere 배포된 IP 주소가 표시됩니다. IP 주소를 기록해 두세요. SnapCenter Plug-in for VMware vSphere 구성을 변경하려면 SnapCenter Plug-in for VMware vSphere 관리 GUI에 로그인해야 합니다.

. 배포 마법사에서 제공한 자격 증명을 사용하여 배포 화면에 표시된 IP 주소를 사용하여 SnapCenter Plug-in for VMware vSphere 에 로그인한 다음, 대시보드에서 SnapCenter Plug-in for VMware vSphere vCenter에 성공적으로 연결되고 활성화되었는지 확인합니다.
+
형식을 사용하세요 `\https://<appliance-IP-address>:8080` 관리 GUI에 접근합니다.

+
배포 시 설정한 관리자 사용자 이름과 비밀번호, 그리고 유지 관리 콘솔을 사용하여 생성된 MFA 토큰을 사용하여 로그인합니다.

. vCenter HTML5 클라이언트에 로그인한 다음 도구 모음에서 *메뉴*를 선택한 다음 * SnapCenter Plug-in for VMware vSphere*을 선택합니다.

