---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere 관리하는 기존 리소스 그룹에 단일 VM 또는 데이터 저장소를 빠르게 추가할 수 있습니다. 
---
= 리소스 그룹에 단일 VM 또는 데이터 저장소 추가
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere 관리하는 기존 리소스 그룹에 단일 VM 또는 데이터 저장소를 빠르게 추가할 수 있습니다.

.이 작업에 관하여
SAN 및 NAS 데이터 저장소는 추가할 수 있지만 VSAN 또는 VVOL 데이터 저장소는 추가할 수 없습니다.

.단계
. vSphere 클라이언트 GUI에서 도구 모음의 *메뉴*를 선택하고 추가하려는 VM이나 데이터 저장소로 이동합니다.
. 왼쪽 탐색기 창에서 VM이나 데이터 저장소를 마우스 오른쪽 버튼으로 클릭하고, * SnapCenter Plug-in for VMware vSphere* > 보조 드롭다운 목록에서 *리소스 그룹에 추가*를 선택합니다.
+
시스템은 먼저 SnapCenter 선택된 VM이 위치한 스토리지 시스템을 관리하고 호환되는지 확인한 다음 *리소스 그룹에 추가* 페이지를 표시합니다.  메시지가 `SnapCenter Compatibility Error` 가 표시되면 선택한 VM이 SnapCenter 와 호환되지 않는 것이므로 먼저 SnapCenter 에 적절한 스토리지 VM을 추가해야 합니다.

. *리소스 그룹에 추가* 페이지에서 리소스 그룹을 선택한 다음 *확인*을 선택합니다.
+
*확인*을 선택하면 시스템은 먼저 SnapCenter 선택된 VM 또는 데이터스토어가 있는 스토리지를 관리하고 호환되는지 확인합니다.

+
메시지가 `Selected <resource-name> is not SnapCenter compatible` 가 표시되면 선택한 VM 또는 데이터 저장소가 SnapCenter 와 호환되지 않는 것입니다. . link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["호환성 검사 실패 관리"] 자세한 내용은.


