---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: 가상화된 머신에서 VM, 데이터 저장소 및 애플리케이션 일관성 데이터베이스를 보호하기 위해 SnapCenter 기능을 사용하려면 SnapCenter Plug-in for VMware vSphere 배포해야 합니다. 
---
= SnapCenter Plug-in for VMware vSphere 배포
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
가상화된 머신에서 VM, 데이터 저장소 및 애플리케이션 일관성 데이터베이스를 보호하기 위해 SnapCenter 기능을 사용하려면 SnapCenter Plug-in for VMware vSphere 배포해야 합니다.

.시작하기 전에
이 섹션에서는 배포를 시작하기 전에 수행해야 하는 모든 필수 작업을 나열합니다.


NOTE: OVA 배포는 VMware vCenter 7u1 이상에서 지원됩니다.

* 배포 요구 사항을 읽어보셨을 겁니다.
* 지원되는 버전의 vCenter Server를 실행해야 합니다.
* vCenter Server 환경을 구성하고 설정해야 합니다.
* SnapCenter Plug-in for VMware vSphere 위해 ESXi 호스트를 설정해야 합니다.
* SnapCenter Plug-in for VMware vSphere .tar 파일을 다운로드했어야 합니다.
* vCenter Server 인스턴스에 대한 로그인 인증 세부 정보가 있어야 합니다.
* 유효한 공개 키와 개인 키 파일이 포함된 인증서가 있어야 합니다.  자세한 내용은 다음 문서를 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_Certificate_Resolution_Guide["저장소 인증서 관리"] 부분.
* SnapCenter Plug-in for VMware vSphere 배포하는 동안 브라우저 캐시 문제가 발생하지 않도록 하려면 vSphere 클라이언트의 모든 브라우저 세션에서 로그아웃하고 닫은 다음 브라우저 캐시를 삭제해야 합니다.
* vCenter에서 TLS(전송 계층 보안)를 활성화해야 합니다.  VMware 설명서를 참조하세요.
* SnapCenter Plug-in for VMware vSphere 배포된 vCenter가 아닌 다른 vCenter에서 백업을 수행하려는 경우 ESXi 서버, SnapCenter Plug-in for VMware vSphere 및 각 vCenter를 동일한 시간으로 동기화해야 합니다.
* vVol 데이터 저장소에서 VM을 보호하려면 먼저 ONTAP tools for VMware vSphere 배포해야 합니다.  지원되는 ONTAP 도구 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구"^] .  ONTAP 도구는 ONTAP 과 VMware 웹 클라이언트에서 스토리지를 프로비저닝하고 구성합니다.


vCenter와 동일한 표준 시간대에 SnapCenter Plug-in for VMware vSphere 배포합니다.  백업 일정은 SnapCenter Plug-in for VMware vSphere 배포된 시간대에 따라 실행됩니다. vCenter는 vCenter가 위치한 시간대에 따라 데이터를 보고합니다.  따라서 SnapCenter Plug-in for VMware vSphere 과 vCenter가 서로 다른 시간대에 있는 경우 SnapCenter Plug-in for VMware vSphere 의 데이터가 보고서의 데이터와 동일하지 않을 수 있습니다.

.단계
. VMware vCenter 7.0.3 이상 버전의 경우 다음 단계를 따르세요.link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance(OVA) 다운로드"^] 인증서를 vCenter로 가져옵니다.
. 브라우저에서 VMware vSphere vCenter로 이동합니다.
+

NOTE: IPv6 주소 HTML 웹 클라이언트의 경우 Chrome이나 Firefox를 사용해야 합니다.

. *VMware vCenter Single Sign-On* 페이지에 로그인합니다.
. 탐색기 창에서 데이터 센터, 클러스터 또는 호스트와 같은 가상 머신의 유효한 상위 개체인 인벤토리 개체를 마우스 오른쪽 버튼으로 클릭하고 *OVF 템플릿 배포*를 선택하여 VMware 배포 마법사를 시작합니다.
. .ova 파일이 포함된 .tar 파일을 로컬 시스템에 추출합니다.  *OVF 템플릿 선택* 페이지에서 위치를 지정하세요. `.ova` .tar 압축 해제된 폴더 내부의 파일입니다.
. *다음*을 선택하세요.
. *이름 및 폴더 선택* 페이지에서 VM 또는 vApp에 대한 고유한 이름을 입력하고 배포 위치를 선택한 후 *다음*을 선택합니다.
+
이 단계에서는 가져올 위치를 지정합니다. `.tar` 파일을 vCenter에 넣습니다.  VM의 기본 이름은 선택한 VM의 이름과 동일합니다. `.ova` 파일.  기본 이름을 변경하는 경우 각 vCenter Server VM 폴더 내에서 고유한 이름을 선택하세요.

+
VM의 기본 배포 위치는 마법사를 시작한 인벤토리 개체입니다.

. *리소스 선택* 페이지에서 배포된 VM 템플릿을 실행할 리소스를 선택하고 *다음*을 선택합니다.
. *리뷰 세부 정보* 페이지에서 다음을 확인하세요. `.tar` 템플릿 세부 정보를 입력하고 *다음*을 선택하세요.
. *라이선스 계약* 페이지에서 *모든 라이선스 계약에 동의합니다* 확인란을 선택합니다.
. *저장소 선택* 페이지에서 배포된 OVF 템플릿의 파일을 저장할 위치와 방법을 정의합니다.
+
.. VMDK의 디스크 형식을 선택합니다.
.. VM 스토리지 정책을 선택하세요.
+
이 옵션은 대상 리소스에서 스토리지 정책이 활성화된 경우에만 사용할 수 있습니다.

.. 배포된 OVA 템플릿을 저장할 데이터 저장소를 선택합니다.
+
구성 파일과 가상 디스크 파일은 데이터 저장소에 저장됩니다.

+
가상 머신이나 vApp 및 연관된 모든 가상 디스크 파일을 수용할 수 있을 만큼 큰 데이터 저장소를 선택하세요.



. *네트워크 선택* 페이지에서 다음을 수행합니다.
+
.. 소스 네트워크를 선택하고 대상 네트워크에 매핑합니다.
+
소스 네트워크 열에는 OVA 템플릿에 정의된 모든 네트워크가 나열됩니다.

.. *IP 할당 설정* 섹션에서 필요한 IP 주소 프로토콜을 선택한 후 *다음*을 선택합니다.
+
SnapCenter Plug-in for VMware vSphere 하나의 네트워크 인터페이스를 지원합니다.  여러 개의 네트워크 어댑터가 필요한 경우 수동으로 설정해야 합니다. 참조하다 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["KB 문서: 추가 네트워크 어댑터를 만드는 방법"^] .



. *템플릿 사용자 지정* 페이지에서 다음을 수행합니다.
+
.. *기존 vCenter에 등록* 섹션에서 vCenter 이름과 가상 어플라이언스의 vCenter 자격 증명을 입력합니다.
+
*vCenter 사용자 이름* 필드에 사용자 이름을 다음 형식으로 입력합니다. `domain\username` .

.. *SCV 자격 증명 만들기* 섹션에 로컬 자격 증명을 입력합니다.
+
*사용자 이름* 필드에 로컬 사용자 이름을 입력합니다. 도메인 세부 정보는 포함하지 마세요.

+

IMPORTANT: 지정한 사용자 이름과 비밀번호를 기록해 두세요.  나중에 SnapCenter Plug-in for VMware vSphere 수정하려면 이러한 자격 증명을 사용해야 합니다.

.. maint 사용자의 자격 증명을 입력하세요.
.. *네트워크 속성 설정* 섹션에서 호스트 이름을 입력합니다.
+
... *IPv4 네트워크 속성 설정* 섹션에서 IPv4 주소, IPv4 넷마스크, IPv4 게이트웨이, IPv4 기본 DNS, IPv4 보조 DNS, IPv4 검색 도메인과 같은 네트워크 정보를 입력합니다.
... *IPv6 네트워크 속성 설정* 섹션에서 IPv6 주소, IPv6 넷마스크, IPv6 게이트웨이, IPv6 기본 DNS, IPv6 보조 DNS, IPv6 검색 도메인과 같은 네트워크 정보를 입력합니다.
+
해당되는 경우 IPv4 또는 IPv6 주소 필드, 또는 둘 다를 선택합니다.  IPv4와 IPv6 주소를 모두 사용하는 경우, 그 중 하나에만 기본 DNS를 지정해야 합니다.

+

IMPORTANT: DHCP를 네트워크 구성으로 사용하려면 이 단계를 건너뛰고 *네트워크 속성 설정* 섹션의 항목을 비워 둘 수 있습니다.



.. *설정 날짜 및 시간*에서 vCenter가 있는 시간대를 선택합니다.


. *완료 준비* 페이지에서 페이지를 검토하고 *마침*을 선택하세요.
+
모든 호스트는 IP 주소로 구성되어야 합니다(FQDN 호스트 이름은 지원되지 않음).  배포 작업은 배포 전에 입력 내용의 유효성을 검사하지 않습니다.

+
OVF 가져오기 및 배포 작업이 완료될 때까지 최근 작업 창에서 배포 진행 상황을 볼 수 있습니다.

+
SnapCenter Plug-in for VMware vSphere 성공적으로 배포되면 Linux VM으로 배포되고 vCenter에 등록되며 VMware vSphere 클라이언트가 설치됩니다.

. SnapCenter Plug-in for VMware vSphere 배포된 VM으로 이동한 다음, *요약* 탭을 선택하고, *전원 켜기* 상자를 선택하여 가상 어플라이언스를 시작합니다.
. SnapCenter Plug-in for VMware vSphere 켜지는 동안 배포된 SnapCenter Plug-in for VMware vSphere 마우스 오른쪽 버튼으로 클릭하고 *게스트 OS*를 선택한 다음 *VMware 도구 설치*를 선택합니다.
+
VMware 도구는 SnapCenter Plug-in for VMware vSphere 배포된 VM에 설치됩니다.  VMware 도구 설치에 대한 자세한 내용은 VMware 설명서를 참조하세요.

+
배포가 완료되기까지 몇 분이 걸릴 수 있습니다.  SnapCenter Plug-in for VMware vSphere 전원이 켜지고, VMware 도구가 설치되고, SnapCenter Plug-in for VMware vSphere 에 로그인하라는 메시지가 화면에 표시되면 배포가 성공적으로 완료된 것입니다.  첫 번째 재부팅 중에 네트워크 구성을 DHCP에서 정적 구성으로 전환할 수 있습니다.  하지만 정적에서 DHCP로의 전환은 지원되지 않습니다.

+
화면에는 SnapCenter Plug-in for VMware vSphere 배포된 IP 주소가 표시됩니다. IP 주소를 기록해 두세요. SnapCenter Plug-in for VMware vSphere 구성을 변경하려면 SnapCenter Plug-in for VMware vSphere 관리 GUI에 로그인해야 합니다.

. 배포 화면에 표시된 IP 주소와 배포 마법사에서 제공한 자격 증명을 사용하여 SnapCenter Plug-in for VMware vSphere 에 로그인한 다음, 대시보드에서 SnapCenter Plug-in for VMware vSphere vCenter에 성공적으로 연결되고 활성화되었는지 확인합니다.
+
형식을 사용하세요 `\https://<appliance-IP-address>:8080` 관리 GUI에 접근합니다.

+
배포 시 설정한 관리자 사용자 이름과 비밀번호, 그리고 유지 관리 콘솔을 사용하여 생성된 MFA 토큰을 사용하여 로그인합니다.

+
SnapCenter Plug-in for VMware vSphere 활성화되지 않은 경우 다음을 참조하세요.link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["VMware vSphere 클라이언트 서비스를 다시 시작합니다."] .

+
호스트 이름이 'UnifiedVSC/SCV'인 경우 어플라이언스를 다시 시작합니다.  어플라이언스를 재시작해도 호스트 이름이 지정된 호스트 이름으로 변경되지 않으면 어플라이언스를 다시 설치해야 합니다.



.당신이 완료한 후
필수 항목을 완료해야 합니다.link:scpivs44_post_deployment_required_operations_and_issues.html["배치 후 작업"] .
