---
sidebar: sidebar 
permalink: scpivs44_upgrade_to_a_new_patch.html 
keywords:  
summary: 동일한 릴리스의 새로운 패치로 업그레이드하는 경우 업그레이드 또는 등록을 하기 전에 vCenter 웹 서버에서 SnapCenter Plug-in for VMware vSphere 지우고 서버를 다시 시작해야 합니다. 
---
= SnapCenter Plug-in for VMware vSphere 의 동일한 릴리스의 새 패치로 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
동일한 릴리스의 새로운 패치로 업그레이드하는 경우 업그레이드 또는 등록을 하기 전에 vCenter 웹 서버에서 SnapCenter Plug-in for VMware vSphere 지우고 서버를 다시 시작해야 합니다.

플러그인 캐시가 지워지지 않으면 다음과 같은 시나리오에서 최근 작업이 대시보드와 작업 모니터에 표시되지 않습니다.

* SnapCenter Plug-in for VMware vSphere vCenter를 사용하여 배포된 후 나중에 동일한 릴리스의 패치로 업그레이드되었습니다.
* SnapCenter VMware 가상 어플라이언스는 vCenter 1에 배포되었습니다.  나중에 SnapCenter Plug-in for VMware vSphere 이 새로운 vCenter2에 등록되었습니다.  SnapCenter Plug-in for VMware vSphere 의 새 인스턴스가 패치를 통해 생성되어 vCenter1에 등록됩니다.  하지만 vCenter1에는 패치가 적용되지 않은 SnapCenter Plug-in for VMware vSphere 의 캐시된 플러그인이 여전히 있으므로 캐시를 지워야 합니다.




[[steps-for-clearing-the-cache]]
== 캐시를 지우는 단계

. 위치 `vsphere-client-serenity` 폴더를 찾은 다음 `com.netapp.scv.client-<release-number>` 폴더를 삭제하세요.
+
폴더 이름은 릴리스마다 변경됩니다.

+
위치는 VMware 설명서를 참조하세요. `vsphere-client-serenity` 운영 체제에 맞는 폴더입니다.

. vCenter Server를 다시 시작합니다.
+
그런 다음 SnapCenter Plug-in for VMware vSphere 업그레이드할 수 있습니다.


