---
sidebar: sidebar 
permalink: scpivs44_customize_your_configuration.html 
keywords:  
summary: 운영 효율성을 개선하려면 scbr.override 구성 파일을 수정하여 기본값을 변경할 수 있습니다.  이러한 값은 백업 중에 생성되거나 삭제되는 VMware 스냅샷 수나 백업 스크립트가 실행을 중지하기 전까지의 시간 등의 설정을 제어합니다. 
---
= 구성을 사용자 정의하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
운영 효율성을 개선하려면 다음을 수정할 수 있습니다. `scbr.override` 기본값을 변경하려면 구성 파일을 사용합니다.  이러한 값은 백업 중에 생성되거나 삭제되는 VMware 스냅샷 수나 백업 스크립트가 실행을 중지하기 전까지의 시간 등의 설정을 제어합니다.

그만큼 `scbr.override` 구성 파일은 SnapCenter 애플리케이션 기반 데이터 보호 작업을 지원하는 SnapCenter Plug-in for VMware vSphere 에서 사용됩니다.  이 파일이 존재하지 않으면 템플릿 파일에서 만들어야 합니다.



[[create-the-scbr-override-configuration-file]]
== scbr.override 구성 파일을 만듭니다.

. 로 가다 `/opt/netapp/scvservice/standalone_aegis/etc/scbr/scbr.override-template` .
. 복사하다 `scbr.override-template` 파일을 새 파일로 변환 `scbr.override` 에서 `\opt\netapp\scvservice\standalone_aegis\etc\scbr` 예배 규칙서.




[[properties-you-can-override]]
== 재정의할 수 있는 속성

* 기본적으로 템플릿은 해시 기호를 사용하여 구성 속성에 주석을 달습니다.  속성을 사용하여 구성 값을 수정하려면 다음을 제거해야 합니다. `#` 문자.
* 변경 사항을 적용하려면 SnapCenter Plug-in for VMware vSphere 에서 서비스를 다시 시작해야 합니다.


다음 속성을 사용할 수 있습니다. `scbr.override` 기본값을 변경하려면 구성 파일을 사용합니다.

* *대시보드.보호된.vm.카운트.간격=7*
+
대시보드에 VM 보호 상태가 표시되는 일수를 지정합니다.

+
기본값은 "7"입니다.

* *guestFileRestore.guest.operation.interval=5*
+
SnapCenter Plug-in for VMware vSphere 게스트에서 게스트 작업(온라인 디스크 및 파일 복원)이 완료되는 것을 모니터링하는 시간 간격(초)을 지정합니다.  총 대기 시간은 다음에 의해 설정됩니다. `guestFileRestore.online.disk.timeout` 그리고 `uestFileRestore.restore.files.timeout` .

+
기본값은 "5"입니다.

* *guestFileRestore.monitorInterval=30*
+
SnapCenter Plug-in for VMware vSphere 만료된 게스트 파일 복원 세션을 모니터링하는 시간 간격(분)을 지정합니다.  구성된 세션 시간을 초과하여 실행되는 모든 세션은 연결이 끊어집니다.

+
기본값은 "30"입니다.

* *guestFileRestore.online.disk.timeout=100*
+
SnapCenter Plug-in for VMware vSphere 게스트 VM에서 온라인 디스크 작업이 완료될 때까지 기다리는 시간(초)을 지정합니다.  플러그인이 온라인 디스크 작업이 완료될 때까지 폴링하기 전에 추가로 30초의 대기 시간이 있다는 점에 유의하세요.

+
기본값은 "100"입니다.

* *guestFileRestore.restore.files.timeout=3600*
+
SnapCenter Plug-in for VMware vSphere 게스트 VM에서 파일 복원 작업이 완료될 때까지 기다리는 시간(초)을 지정합니다.  시간이 초과되면 프로세스가 종료되고 작업은 실패로 표시됩니다.

+
기본값은 "3600"(1시간)입니다.

* *guestFileRestore.robocopy.directory.flags=/R:0 /W:0 /ZB /모두 복사 /EFSRAW /A-:SH /e /NJH /NDL /NP*
+
게스트 파일 복원 작업 중에 디렉토리를 복사할 때 사용할 추가 robocopy 플래그를 지정합니다.

+
제거하지 마세요 `/NJH` 또는 추가 `/NJS` 이렇게 하면 복원 출력의 구문 분석이 중단되기 때문입니다.

+
무제한 재시도를 허용하지 마십시오(제거하여) `/R` (플래그) 이렇게 하면 실패한 복사에 대해 무한정 재시도가 발생할 수 있습니다.

+
기본값은 다음과 같습니다. `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /e /NJH /NDL /NP"` .

* *guestFileRestore.robocopy.file.flags=/R:0 /W:0 /ZB /모두 복사 /EFSRAW /A-:SH /NJH /NDL /NP*
+
게스트 파일 복원 작업 중에 개별 파일을 복사할 때 사용할 추가 Robocopy 플래그를 지정합니다.

+
제거하지 마세요 `/NJH` 또는 추가 `/NJS` 이렇게 하면 복원 출력의 구문 분석이 중단되기 때문입니다.

+
무제한 재시도를 허용하지 마십시오(제거하여) `/R` (플래그) 이렇게 하면 실패한 복사에 대해 무한정 재시도가 발생할 수 있습니다.

+
기본값은 다음과 같습니다. `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /NJH /NDL /NP"` .

* *guestFileRestore.sessionTime=1440*
+
SnapCenter Plug-in for VMware vSphere 게스트 파일 복원 세션을 활성 상태로 유지하는 시간(분)을 지정합니다.

+
기본값은 "1440"(24시간)입니다.

* *guestFileRestore.use.custom.online.disk.script=true*
+
게스트 파일 복원 세션을 생성할 때 디스크를 온라인으로 전환하고 드라이브 문자를 검색하기 위해 사용자 지정 스크립트를 사용할지 여부를 지정합니다.  스크립트는 다음 위치에 있어야 합니다. `[Install Path]  \etc\guestFileRestore_onlineDisk.ps1` .  설치 시 기본 스크립트가 제공됩니다.  가치 `[Disk_Serial_Number]` , `[Online_Disk_Output]` , 그리고 `[Drive_Output]` 스크립트에서 첨부 프로세스 중에 대체됩니다.

+
기본값은 "false"입니다.

* *include.esx.initiator.id.from.cluster=true*
+
SnapCenter Plug-in for VMware vSphere VMDK 워크플로를 통해 애플리케이션의 클러스터에 있는 모든 ESXi 호스트의 iSCSI 및 FCP 이니시에이터 ID를 포함해야 함을 지정합니다.

+
기본값은 "false"입니다.

* *최대.동시.ds.스토리지.쿼리.수=15*
+
SnapCenter Plug-in for VMware vSphere 데이터스토어의 스토리지 공간을 검색하기 위해 SnapCenter 서버에 동시에 호출할 수 있는 최대 호출 수를 지정합니다.  이 플러그인은 SnapCenter Plug-in for VMware vSphere 에서 Linux 서비스를 다시 시작할 때 이러한 호출을 수행합니다.

* *nfs.데이터스토어.마운트.재시도.횟수=3*
+
SnapCenter Plug-in for VMware vSphere vCenter에서 볼륨을 NFS 데이터스토어로 마운트하려고 시도하는 최대 횟수를 지정합니다.

+
기본값은 "3"입니다.

* *nfs.데이터스토어.마운트.재시도.지연=60000*
+
SnapCenter Plug-in for VMware vSphere vCenter에서 볼륨을 NFS 데이터스토어로 마운트하려고 시도하는 사이에 기다리는 시간(밀리초)을 지정합니다.

+
기본값은 "60000"(60초)입니다.

* *스크립트.가상.머신.개수.변수.이름= 가상 머신*
+
가상 머신 수가 포함된 환경 변수 이름을 지정합니다.  백업 작업 중에 사용자 정의 스크립트를 실행하기 전에 변수를 정의해야 합니다.

+
예를 들어, VIRTUAL_MACHINES=2는 두 개의 가상 머신이 백업된다는 것을 의미합니다.

* *스크립트.가상.기계.정보.변수.이름=가상_기계.%s*
+
백업에서 n번째 가상 머신에 대한 정보가 포함된 환경 변수의 이름을 제공합니다.  백업 중에 사용자 정의 스크립트를 실행하기 전에 이 변수를 설정해야 합니다.

+
예를 들어, 환경 변수 VIRTUAL_MACHINE.2는 백업의 두 번째 가상 머신에 대한 정보를 제공합니다.

* *스크립트.가상.머신.정보.형식= %s|%s|%s|%s|%s*
+
가상 머신에 대한 정보를 제공합니다.  환경 변수에 설정된 이 정보의 형식은 다음과 같습니다. `VM name|VM UUID| VM power state (on|off)|VM snapshot taken (true|false)|IP address(es)`

+
다음은 귀하가 제공할 수 있는 정보의 예입니다.

+
`VIRTUAL_MACHINE.2=VM 1|564d6769-f07d-6e3b-68b1f3c29ba03a9a|POWERED_ON||true|10.0.4.2`

* *저장소.연결.시간 초과=600000*
+
SnapCenter 서버가 스토리지 시스템으로부터 응답을 기다리는 시간(밀리초)을 지정합니다.

+
기본값은 "600000"(10분)입니다.

* *vmware.esx.ip.커널.ip.맵*
+
기본값은 없습니다.  이 값을 사용하여 ESXi IP 주소를 VMkernel IP 주소에 매핑합니다.  기본적으로 SnapCenter Plug-in for VMware vSphere ESXi 호스트의 관리 VMkernel 어댑터 IP 주소를 사용합니다.  SnapCenter Plug-in for VMware vSphere 다른 VMkernel 어댑터 IP 주소를 사용하도록 하려면 재정의 값을 제공해야 합니다.

+
다음 예에서 관리 VMkernel 어댑터 IP 주소는 10.225.10.56입니다. 하지만 SnapCenter Plug-in for VMware vSphere 지정된 주소인 10.225.11.57과 10.225.11.58을 사용합니다.  관리 VMkernel 어댑터 IP 주소가 10.225.10.60이면 플러그인은 주소 10.225.11.61을 사용합니다.

+
`vmware.esx.ip.kernel.ip.map=10.225.10.56:10.225.11.57,10.225.11.58; 10.225.10.60:10.225.11.61`

* *vmware.max.동시.스냅샷=30*
+
SnapCenter Plug-in for VMware vSphere 서버에서 수행하는 동시 VMware 스냅샷의 최대 수를 지정합니다.

+
이 숫자는 데이터 저장소별로 확인되며 정책에서 "VM 일관성"이 선택된 경우에만 확인됩니다.  충돌 일관성 백업을 수행하는 경우 이 설정은 적용되지 않습니다.

+
기본값은 "30"입니다.

* *vmware.max.concurrent.snapshots.delete=30*
+
SnapCenter Plug-in for VMware vSphere 서버에서 수행하는 데이터스토어당 동시 VMware 스냅샷 삭제 작업의 최대 수를 지정합니다.

+
이 숫자는 데이터 저장소별로 확인됩니다.

+
기본값은 "30"입니다.

* *vmware.query.미해결.재시도.횟수=10*
+
SnapCenter Plug-in for VMware vSphere "...I/O 보류 시간 제한..." 오류로 인해 해결되지 않은 볼륨에 대한 쿼리를 전송하는 최대 횟수를 지정합니다.

+
기본값은 "10"입니다.

* *vmware.quiesce.retry.count=0*
+
백업 중에 "...I/O 보류 시간 제한..." 오류로 인해 SnapCenter Plug-in for VMware vSphere VMware 스냅샷에 대한 쿼리를 전송하는 최대 횟수를 지정합니다.

+
기본값은 "0"입니다.

* *vmware.quiesce.retry.interval=5*
+
SnapCenter Plug-in for VMware vSphere 백업 중에 VMware 스냅샷 "...I/O 보류 시간 제한..." 오류에 대한 쿼리를 보내는 사이에 기다리는 시간(초)을 지정합니다.

+
기본값은 "5"입니다.

* *vmware.query.미해결.재시도.지연= 60000*
+
"...I/O 보류 시간 제한..." 오류로 인해 해결되지 않은 볼륨에 대한 쿼리를 보내는 사이에 SnapCenter Plug-in for VMware vSphere 기다리는 시간(밀리초)을 지정합니다.  이 오류는 VMFS 데이터 저장소를 복제할 때 발생합니다.

+
기본값은 "60000"(60초)입니다.

* *vmware.reconfig.vm.retry.count=10*
+
SnapCenter Plug-in for VMware vSphere "...I/O 보류 시간 제한..." 오류로 인해 VM 재구성에 대한 쿼리를 전송하는 최대 횟수를 지정합니다.

+
기본값은 "10"입니다.

* *vmware.reconfig.vm.retry.delay=30000*
+
"...I/O 보류 시간 제한..." 오류로 인해 VM을 재구성하는 것과 관련된 쿼리를 보내는 사이에 SnapCenter Plug-in for VMware vSphere 기다리는 최대 시간(밀리초)을 지정합니다.

+
기본값은 "30000"(30초)입니다.

* *vmware.rescan.hba.재시도.횟수=3*
+
SnapCenter Plug-in for VMware vSphere "...I/O 보류 시간 제한..." 오류로 인해 호스트 버스 어댑터를 다시 스캔하는 것과 관련된 쿼리를 보내는 사이에 기다리는 시간(밀리초)을 지정합니다.

+
기본값은 "3"입니다.

* *vmware.rescan.hba.재시도.지연=30000*
+
SnapCenter Plug-in for VMware vSphere 호스트 버스 어댑터를 다시 스캔하기 위한 요청을 재시도하는 최대 횟수를 지정합니다.

+
기본값은 "30000"입니다.


