---
sidebar: sidebar 
permalink: scpivs44_migration_overview.html 
keywords:  
summary:  
---
= 마이그레이션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
마이그레이션 명령은 SnapCenter 4.0 이상에서만 메타데이터를 마이그레이션합니다.  이전 버전의 SnapCenter 사용하는 경우 마이그레이션하기 전에 먼저 업그레이드해야 합니다.

* 마이그레이션된 내용에는 다음이 포함됩니다.
+
** 무엇이 마이그레이션 되나요?
+
SnapCenter 구성 파일의 스토리지 시스템, 사용자 정의 제한 및 이메일 설정, 정책, 리소스 그룹, 백업 메타데이터 및 마운트를 포함하는 SnapCenter 메타데이터입니다.  (전술문이나 후술문을 만나면 마이그레이션이 실패함)

** 마이그레이션되지 않는 것은 무엇입니까?
+
리소스 그룹에 대해 구성된 사전 및 사후 스크립트

+
활성 게스트 파일 복원 세션, 게스트 파일 복원 자격 증명 및 프록시 VM

+
게스트 파일 복원 세션이 활성화되어 있을 때 마이그레이션을 시작하면 세션이 삭제되고 연결된 디스크는 마운트 해제되지 않습니다.  첨부된 디스크를 수동으로 삭제해야 할 수도 있습니다.

+
`scbr.override`구성 파일



* SnapCenter 호스트가 일시 중단되었습니다.
+
마이그레이션이 성공적으로 이루어지도록 마이그레이션 명령은 SnapCenter 에 등록된 모든 호스트를 일시 중단합니다.  마이그레이션 프로세스가 성공적으로 완료되면 SnapCenter 호스트가 다시 시작됩니다.

* 마이그레이션 cmdlet 프로세스
+
Windows PowerShell cmdlet을 사용해야 합니다. `invoke-SCVOVAMigration` SnapCenter 에 등록된 SnapCenter Plug-in for VMware vSphere 의 각 인스턴스에 대해.

+
cmdlet은 다음을 수행합니다.

+
** 마이그레이션 중에 작업 실패를 방지하기 위해 모든 일정을 일시 중단합니다.  마이그레이션이 성공적으로 완료되면 일정이 자동으로 다시 활성화됩니다.
** 저장소 연결과 메타데이터를 마이그레이션합니다.
** 마이그레이션 후 백업을 위한 백업 일정을 만듭니다.
** Windows 호스트에서 SnapCenter Plug-in for VMware vSphere 제거합니다.
+
SnapCenter 서버 호스트에 SnapCenter Plug-in for VMware vSphere 설치되어 있고 SnapCenter 저장소에 대한 보호가 구성된 경우, 마이그레이션 프로세스는 SnapCenter Plug-in for VMware vSphere 과 Windows용 SnapCenter 플러그인이 포함된 Windows 기반 플러그인 패키지도 제거한 다음, 저장소 보호를 지원하기 위해 Windows용 SnapCenter 플러그인의 최신 버전을 다시 설치합니다. SnapCenter GUI의 호스트 유형이 "vsphere"에서 "Windows"로 변경되었습니다.

** Windows SnapCenter 서버에서 vSphere 호스트와 리소스 그룹을 제거합니다.
** SnapCenter Plug-in for VMware vSphere 에서 백업 작업을 활성화합니다.
** 가상화된 데이터베이스와 파일 시스템의 애플리케이션 기반 백업(VMDK 백업을 통한 애플리케이션)을 지원하기 위해 SnapCenter Plug-in for VMware vSphere 용 vSphere 호스트를 SnapCenter 에 등록합니다.


* 메타데이터가 저장되는 위치
+
애플리케이션 기반 VMDK 백업에 대한 메타데이터는 SnapCenter 서버 저장소에 저장됩니다.  VM 및 데이터 저장소 백업에 대한 메타데이터는 SnapCenter Plug-in for VMware vSphere 에 저장됩니다.


