---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: 'Windows 게스트 OS의 가상 머신 디스크(VMDK)에서 파일이나 폴더를 복원할 수 있습니다.' 
---
= 워크플로, 전제 조건 및 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 게스트 OS의 가상 머신 디스크(VMDK)에서 파일이나 폴더를 복원할 수 있습니다.



== 게스트 복원 워크플로

게스트 OS 복원 작업에는 다음 단계가 포함됩니다.

. 붙이다
+
게스트 VM이나 프록시 VM에 가상 디스크를 연결하고 게스트 파일 복원 세션을 시작합니다.

. 기다리다
+
찾아보고 복원하기 전에 첨부 작업이 완료될 때까지 기다리세요.  첨부할 때

+
작업이 완료되면 게스트 파일 복원 세션이 자동으로 생성되고 이메일 알림이 전송됩니다.

+
전송된.

. 파일 또는 폴더 선택
+
게스트 파일 복원 세션에서 VMDK를 탐색하고 복원할 파일이나 폴더를 하나 이상 선택합니다.

. 복원하다
+
선택한 파일이나 폴더를 지정된 위치로 복원합니다.





== 게스트 파일 및 폴더 복원을 위한 전제 조건

Windows 게스트 OS의 VMDK에서 하나 이상의 파일이나 폴더를 복원하기 전에 모든 요구 사항을 알아야 합니다.

* VMware 도구가 설치되어 실행 중이어야 합니다.
+
SnapCenter VMware 도구의 정보를 사용하여 VMware Guest OS에 대한 연결을 설정합니다.

* Windows 게스트 OS는 Windows Server 2008 R2 이상을 실행해야 합니다.
+
지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구(IMT)"^] .

* 대상 VM에 대한 자격 증명은 기본 제공 도메인 관리자 계정이나 기본 제공 로컬 관리자 계정을 지정해야 합니다.  사용자 이름은 "관리자"여야 합니다.  복원 작업을 시작하기 전에 가상 디스크를 연결할 VM에 대한 자격 증명을 구성해야 합니다.  자격 증명은 첨부 작업과 그에 따른 복원 작업 모두에 필요합니다.  작업 그룹 사용자는 기본 제공 로컬 관리자 계정을 사용할 수 있습니다.
+

IMPORTANT: 기본 관리자 계정이 아니지만 VM 내에서 관리자 권한이 있는 계정을 사용해야 하는 경우 게스트 VM에서 UAC를 비활성화해야 합니다.

* 복원할 백업 스냅샷과 VMDK를 알아야 합니다.
+
SnapCenter Plug-in for VMware vSphere 복원할 파일이나 폴더를 검색하는 기능을 지원하지 않습니다.  따라서 시작하기 전에 스냅샷과 해당 VMDK와 관련된 파일이나 폴더의 위치를 ​​알아야 합니다.

* 연결할 가상 디스크는 SnapCenter 백업에 있어야 합니다.
+
복원하려는 파일이나 폴더가 포함된 가상 디스크는 SnapCenter Plug-in for VMware vSphere 의 가상 어플라이언스를 사용하여 수행된 VM 백업에 있어야 합니다.

* 프록시 VM을 사용하려면 프록시 VM을 구성해야 합니다.
+
가상 디스크를 프록시 VM에 연결하려면 연결 및 복원 작업을 시작하기 전에 프록시 VM을 구성해야 합니다.

* 영어 알파벳이 아닌 이름을 가진 파일의 경우 단일 파일이 아닌 디렉토리에 복원해야 합니다.
+
일본어 간지와 같이 알파벳이 아닌 이름을 가진 파일은 해당 파일이 위치한 디렉토리를 복원하여 복원할 수 있습니다.

* Linux 게스트 OS에서 복원하는 것은 지원되지 않습니다.
+
Linux 게스트 OS를 실행하는 VM에서는 파일과 폴더를 복원할 수 없습니다.  하지만 VMDK를 첨부한 다음 파일과 폴더를 수동으로 복원할 수 있습니다.  지원되는 게스트 OS에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구(IMT)"^] .





== 게스트 파일 복원 제한 사항

게스트 OS에서 파일이나 폴더를 복원하기 전에 해당 기능이 지원하지 않는 사항이 무엇인지 알아야 합니다.

* 게스트 OS 내부에서는 동적 디스크 유형을 복원할 수 없습니다.
* 암호화된 파일이나 폴더를 복원하면 암호화 속성이 유지되지 않습니다.  암호화된 폴더에는 파일이나 폴더를 복원할 수 없습니다.
* 게스트 파일 찾아보기 페이지에는 필터링할 수 없는 숨겨진 파일과 폴더가 표시됩니다.
* Linux 게스트 OS에서는 복원할 수 없습니다.
+
Linux 게스트 OS를 실행하는 VM에서는 파일과 폴더를 복원할 수 없습니다.  하지만 VMDK를 첨부한 다음 파일과 폴더를 수동으로 복원할 수 있습니다.  지원되는 게스트 OS에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구(IMT)"^] .

* NTFS 파일 시스템에서 FAT 파일 시스템으로 복원할 수 없습니다.
+
NTFS 포맷에서 FAT 포맷으로 복원하려고 하면 FAT 파일 시스템이 Windows 보안 속성을 지원하지 않기 때문에 NTFS 보안 설명자가 복사되지 않습니다.

* 복제된 VMDK나 초기화되지 않은 VMDK에서는 게스트 파일을 복원할 수 없습니다.
* 파일의 디렉토리 구조를 복원할 수 없습니다.
+
중첩된 디렉토리에 있는 파일을 복원하도록 선택한 경우, 해당 파일은 동일한 디렉토리 구조로 복원되지 않습니다.  디렉토리 트리는 복구되지 않고 파일만 복구됩니다.  디렉토리 트리를 복원하려면 디렉토리 자체를 구조의 맨 위에 복사하면 됩니다.

* vVol VM에서 다른 호스트로 게스트 파일을 복원할 수 없습니다.
* 암호화된 게스트 파일은 복구할 수 없습니다.

