---
sidebar: sidebar 
permalink: scpivs44_manage_storage_systems.html 
keywords:  
summary: VMware vSphere 클라이언트를 사용하여 VM이나 데이터 저장소를 백업하거나 복원하려면 먼저 스토리지를 추가해야 합니다. 
---
= 저장 시스템 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware vSphere 클라이언트를 사용하여 VM이나 데이터 저장소를 백업하거나 복원하려면 먼저 스토리지를 추가해야 합니다.



== 스토리지 VM 수정

VMware vSphere 클라이언트를 사용하면 SnapCenter Plug-in for VMware vSphere 에 등록되어 VM 데이터 보호 작업에 사용되는 클러스터 및 스토리지 VM의 구성을 수정할 수 있습니다.

클러스터의 일부로 자동으로 추가된 스토리지 VM(때때로 암묵적 스토리지 VM이라고도 함)을 수정하는 경우 해당 스토리지 VM은 명시적 스토리지 VM으로 변경되며 해당 클러스터의 나머지 스토리지 VM을 변경하지 않고도 별도로 삭제할 수 있습니다.  저장소 시스템 페이지에서 인증 방법이 인증서를 통한 경우 사용자 이름은 N/A로 표시됩니다. 사용자 이름은 클러스터 목록에 있는 명시적 저장소 VM에 대해서만 표시되며 ExplicitSVM 플래그가 true로 설정되어 있습니다.  모든 스토리지 VM은 항상 연관된 클러스터 아래에 나열됩니다.


IMPORTANT: SnapCenter GUI를 사용하여 애플리케이션 기반 데이터 보호 작업에 대한 스토리지 VM을 추가한 경우 동일한 GUI를 사용하여 해당 스토리지 VM을 수정해야 합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *저장 시스템*을 선택합니다.
. *스토리지 시스템* 페이지에서 수정할 스토리지 VM을 선택한 다음 *편집*을 선택합니다.
. *스토리지 시스템 편집* 창에서 새 값을 입력한 다음 *업데이트*를 선택하여 변경 사항을 적용합니다.




== 스토리지 VM 제거

VMware vSphere 클라이언트를 사용하여 vCenter의 인벤토리에서 스토리지 VM을 제거할 수 있습니다.


NOTE: SnapCenter GUI를 사용하여 애플리케이션 기반 데이터 보호 작업에 대한 스토리지 VM을 추가한 경우 동일한 GUI를 사용하여 해당 스토리지 VM을 수정해야 합니다.

.시작하기 전에
스토리지 VM을 제거하려면 먼저 스토리지 VM에 있는 모든 데이터스토어를 마운트 해제해야 합니다.

.이 작업에 관하여
리소스 그룹에 제거한 스토리지 VM에 상주하는 백업이 있는 경우 해당 리소스 그룹에 대한 후속 백업은 실패합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *저장 시스템*을 선택합니다.
. *스토리지 시스템* 페이지에서 제거할 스토리지 VM을 선택한 다음 *삭제*를 선택합니다.
. *스토리지 시스템 제거* 확인 상자에서 *스토리지 시스템 삭제* 상자를 선택한 다음 *예*를 선택하여 확인합니다.  *참고:* ESXi 호스트 7.0U1 이상 릴리스만 지원됩니다.
+
link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["VMware vSphere 클라이언트 서비스를 다시 시작합니다."] .


