---
sidebar: sidebar 
permalink: scpivs44_restore_vms_from_backups.html 
keywords:  
summary: VM을 복원할 때 선택한 백업 사본으로 기존 콘텐츠를 덮어쓰거나 VM의 사본을 만들 수 있습니다. 
---
= 백업에서 VM 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VM을 복원할 때 선택한 백업 사본으로 기존 콘텐츠를 덮어쓰거나 VM의 사본을 만들 수 있습니다.

다음 위치에 VM을 복원할 수 있습니다.

* 원래 위치로 복원
+
** 원래 ESXi 호스트에 마운트된 원래 데이터 저장소로(이렇게 하면 원래 VM이 덮어씌워짐)


* 대체 위치로 복원
+
** 원래 ESXi 호스트에 마운트된 다른 데이터 저장소로
** 동일한 vCenter에서 관리하는 다른 ESXi 호스트에 마운트된 원래 데이터 저장소로
** 동일한 vCenter에서 관리하는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소로
** 다른 vCenter에서 연결된 모드로 관리되는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소로





NOTE: vVol VM을 대체 호스트로 복원할 수 없습니다.


NOTE: 다음 복원 워크플로는 지원되지 않습니다. 스토리지 VM을 추가한 다음 해당 VM의 백업을 수행하고, 스토리지 VM을 삭제하고 동일한 스토리지 VM을 포함하는 클러스터를 추가한 다음 원래 백업을 복원해 봅니다.


TIP: NFS 환경에서 복원 작업의 성능을 향상시키려면 VMware 애플리케이션 vStorage API for Array Integration(VAAI)을 활성화하세요.

.시작하기 전에
* 백업이 반드시 존재해야 합니다.
+
VM을 복원하려면 먼저 SnapCenter Plug-in for VMware vSphere 사용하여 VM 백업을 만들어야 합니다.

+

NOTE: SnapCenter Plug-in for VMware vSphere 아닌 다른 소프트웨어에서 수행된 VM 스냅샷이 있는 경우 복원 작업을 성공적으로 완료할 수 없습니다.

* 대상 데이터 저장소가 준비되어야 합니다.
+
** 복원 작업을 위한 대상 데이터 저장소에는 모든 VM 파일(예: vmdk, vmx, vmsd)의 복사본을 수용할 수 있는 충분한 공간이 있어야 합니다.
** 대상 데이터 저장소에는 이전 복원 작업 실패로 인해 발생한 오래된 VM 파일이 포함되어서는 안 됩니다.  오래된 파일에는 다음과 같은 이름이 있습니다. `restore_xxx_xxxxxx_<filename>` .


* VM은 전송 중이어서는 안 됩니다.
+
복원하려는 VM은 vMotion 또는 Storage vMotion 상태가 아니어야 합니다.

* HA 구성 오류
+
백업을 다른 위치로 복원하기 전에 vCenter ESXi 호스트 요약 화면에 HA 구성 오류가 표시되지 않았는지 확인하세요.

* 다른 위치로 복원
+
** 다른 위치로 복원할 경우 SnapCenter Plug-in for VMware vSphere 복원 작업의 대상인 vCenter에서 실행되어야 합니다.  대상 데이터 저장소에는 충분한 공간이 있어야 합니다.
** 복원 대상 대체 위치 필드의 대상 vCenter는 DNS로 확인 가능해야 합니다.




.이 작업에 관하여
* VM 등록이 해제되었다가 다시 등록되었습니다.
+
VM에 대한 복원 작업은 원래 VM의 등록을 취소하고, 백업 스냅샷에서 VM을 복원하고, 복원된 VM을 동일한 ESXi 서버에 동일한 이름과 구성으로 등록합니다.  복원 후에는 VM을 리소스 그룹에 수동으로 추가해야 합니다.

* 데이터 저장소 복원
+
데이터 저장소는 복원할 수 없지만 데이터 저장소에 있는 모든 VM은 복원할 수 있습니다.

* vVol VM 복원
+
** 여러 VM에 걸쳐 있는 vVol 데이터 저장소는 지원되지 않습니다.  VM에 걸쳐 있는 vVol 데이터 저장소에 연결된 VMDK는 백업되지 않으므로 복원된 VM에는 일부 VMDK만 포함됩니다.
** vVol을 대체 호스트로 복원할 수 없습니다.
** vVol 자동 재조정은 지원되지 않습니다.


* VM에 대한 VMware 일관성 스냅샷 실패
+
VM에 대한 VMware 일관성 스냅샷이 실패하더라도 VM은 백업됩니다.  복원 마법사에서 백업 사본에 포함된 엔터티를 보고 복원 작업에 사용할 수 있습니다.

* VM이 있는 FabricPool 의 스토리지 계층을 사용할 수 없는 경우 복원 작업이 실패할 수 있습니다.


.단계
. VMware vSphere 클라이언트 GUI에서 도구 모음의 *메뉴*를 선택한 다음 드롭다운 목록에서 *VM 및 템플릿*을 선택합니다.
+

NOTE: 삭제된 VM을 복원하는 경우 SnapCenter Plug-in for VMware vSphere 에 추가된 스토리지 VM 자격 증명이 있어야 합니다. `vsadmin` 또는 동일한 모든 권한을 가진 사용자 계정 `vsadmin` .

. 왼쪽 탐색기 창에서 VM을 마우스 오른쪽 버튼으로 클릭한 다음 드롭다운 목록에서 * SnapCenter Plug-in for VMware vSphere*을 선택하고, 보조 드롭다운 목록에서 *복원*을 선택하여 마법사를 시작합니다.
. *복원* 마법사의 *백업 선택* 페이지에서 복원하려는 백업 스냅샷을 선택합니다.
+
특정 백업 이름이나 일부 백업 이름을 검색할 수도 있고, 필터 아이콘을 선택하고 날짜 및 시간 범위를 선택한 다음, VMware 스냅샷이 포함된 백업을 원하는지 여부, 마운트된 백업을 원하는지 여부, 위치를 선택하여 백업 목록을 필터링할 수 있습니다.  마법사로 돌아가려면 *확인*을 선택하세요.

. *범위 선택* 페이지에서 *복원 범위* 필드에서 *전체 가상 머신*을 선택한 다음, 복원 위치를 선택하고 백업을 마운트할 대상 정보를 입력합니다.
+
*VM 이름* 필드에 동일한 VM 이름이 있는 경우 새 VM 이름 형식은 다음과 같습니다. `<vm_name>_<timestamp>` .

+
부분 백업을 복원할 때 복원 작업은 *범위 선택* 페이지를 건너뜁니다.

. *위치 선택* 페이지에서 복원된 데이터 저장소의 위치를 선택합니다.
+
SnapCenter Plug-in for VMware vSphere 에서는 FlexGroup 볼륨에 대한 보조 스토리지를 선택할 수 있습니다.

. 요약 페이지를 검토한 후 *마침*을 선택하세요.
. 선택 사항: 화면 하단의 *최근 작업*을 선택하여 작업 진행 상황을 모니터링합니다.
+
최신 정보를 표시하려면 화면을 새로 고칩니다.



.당신이 완료한 후
* IP 주소 변경
+
다른 위치로 복원한 경우 정적 IP 주소가 구성될 때 IP 주소 충돌을 방지하기 위해 새로 만든 VM의 IP 주소를 변경해야 합니다.

* 복구된 VM을 리소스 그룹에 추가합니다.
+
VM이 복구되더라도 이전 리소스 그룹에 자동으로 추가되지는 않습니다.  따라서 복원된 VM을 적절한 리소스 그룹에 수동으로 추가해야 합니다.


