---
sidebar: sidebar 
permalink: scpivs44_ontap_rbac_features_in_snapcenter.html 
keywords:  
summary: 'SnapCenter Plug-in for VMware vSphere vCenter Server RBAC, SnapCenter RBAC(애플리케이션 기반 작업을 지원하는 데 필요한 경우), ONTAP RBAC와 함께 작동하여 특정 사용자가 특정 스토리지 시스템의 개체에 대해 수행할 수 있는 SnapCenter 작업을 결정합니다.' 
---
= SnapCenter Plug-in for VMware vSphere 의 ONTAP RBAC 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: ONTAP RBAC는 SnapCenter Server 애플리케이션 일관성(VMDK를 통한 애플리케이션) 작업에만 적용됩니다.

[role="lead"]
ONTAP 역할 기반 액세스 제어(RBAC)를 사용하면 특정 스토리지 시스템에 대한 액세스와 사용자가 해당 스토리지 시스템에서 수행할 수 있는 작업을 제어할 수 있습니다.  SnapCenter Plug-in for VMware vSphere vCenter Server RBAC, SnapCenter RBAC(애플리케이션 기반 작업을 지원하는 데 필요한 경우), ONTAP RBAC와 함께 작동하여 특정 사용자가 특정 스토리지 시스템의 개체에 대해 수행할 수 있는 SnapCenter 작업을 결정합니다.

SnapCenter 사용자가 설정한 자격 증명(사용자 이름 및 비밀번호)을 사용하여 각 스토리지 시스템을 인증하고 해당 스토리지 시스템에서 수행할 수 있는 작업을 결정합니다.  SnapCenter Plug-in for VMware vSphere 각 스토리지 시스템에 대해 하나의 자격 증명 세트를 사용합니다.  이러한 자격 증명은 해당 스토리지 시스템에서 수행할 수 있는 모든 작업을 결정합니다. 즉, 이 자격 증명은 개별 SnapCenter 사용자가 아닌 SnapCenter 위한 것입니다.

ONTAP RBAC는 스토리지 시스템에 액세스하고 VM 백업과 같은 스토리지와 관련된 SnapCenter 작업을 수행하는 경우에만 적용됩니다.  특정 스토리지 시스템에 대한 적절한 ONTAP RBAC 권한이 없으면 해당 스토리지 시스템에 호스팅된 vSphere 개체에서 어떠한 작업도 수행할 수 없습니다.

각 스토리지 시스템에는 연관된 ONTAP 권한 세트가 하나씩 있습니다.

ONTAP RBAC와 vCenter Server RBAC를 모두 사용하면 다음과 같은 이점이 있습니다.

* 보안
+
관리자는 세분화된 vCenter Server 개체 수준과 스토리지 시스템 수준에서 어떤 사용자가 어떤 작업을 수행할 수 있는지 제어할 수 있습니다.

* 감사 정보
+
많은 경우 SnapCenter 스토리지 시스템에 대한 감사 추적 기능을 제공하여 스토리지 수정을 수행한 vCenter 사용자까지 이벤트를 추적할 수 있습니다.

* 사용성
+
컨트롤러 자격 증명을 한 곳에서 관리할 수 있습니다.


