---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vms.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere 사용하여 VM 백업에 대한 복원 작업을 수행하려면 규정된 REST API 호출 순서를 따라야 합니다. 
---
= VM을 복원하기 위한 REST API 워크플로
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere 사용하여 VM 백업에 대한 복원 작업을 수행하려면 규정된 REST API 호출 순서를 따라야 합니다.

각 REST API에 대해 다음을 추가합니다. `\https://<server>:<port>` REST API의 전면에 위치하여 완전한 엔드포인트를 형성합니다.

|===
| 단계 | REST API | 댓글 


| 1 | 로 가다 `\http://<vCenter-IP>/mob` | 자세한 내용은 VMware Managed Objects URL에서 확인하세요.  복원하려는 VM에 대한 *moref*를 참고하세요. 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups`지정된 VM에 대한 백업 목록을 가져옵니다.  1단계의 *moref*를 전달하세요.  복원하려는 백업의 *backupId*를 기록해 두세요. 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations`지정된 백업에 대한 스냅샷의 위치를 가져옵니다.  2단계의 *backupId*를 전달합니다.  *snapshotLocationsList* 정보를 참고하세요. 


| 4 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts`백업이 저장된 호스트에 대한 정보를 가져옵니다.  *availableEsxHostsList* 정보를 확인하세요. 


| 5 | `/4.1/vm/{moref}/backups/
{backupId}/restore`  a| 
`Restore a VM from a backup`지정된 백업을 복원합니다.  3단계와 4단계의 정보를 *restoreLocations* 속성에 전달합니다.


NOTE: VM 백업이 부분 백업인 경우 다음을 설정합니다. `restartVM` 매개변수를 "false"로 설정합니다.


NOTE: 템플릿인 VM은 복원할 수 없습니다.

|===