---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: 더 이상 SnapCenter 데이터 보호 기능을 사용할 필요가 없는 경우 SnapCenter Plug-in for VMware vSphere 비활성화하여 vCenter에서 등록을 취소한 다음, vCenter에서 SnapCenter Plug-in for VMware vSphere 제거한 후 남아 있는 파일을 수동으로 삭제해야 합니다. 
---
= SnapCenter Plug-in for VMware vSphere 제거
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
더 이상 SnapCenter 데이터 보호 기능을 사용할 필요가 없는 경우 SnapCenter Plug-in for VMware vSphere 비활성화하여 vCenter에서 등록을 취소한 다음, vCenter에서 SnapCenter Plug-in for VMware vSphere 제거한 후 남아 있는 파일을 수동으로 삭제해야 합니다.

.시작하기 전에
* 관리자 권한이 있어야 합니다.
* SnapCenter 작업이 실행되고 있지 않은지 확인하세요.


.단계
. 다음 형식을 사용하여 SnapCenter Plug-in for VMware vSphere 에 로그인합니다. `\https://<OVA-IP-address>:8080` .
+
SnapCenter Plug-in for VMware vSphere 의 IP 주소는 플러그인을 배포할 때 표시됩니다.

. 왼쪽 탐색 창에서 *구성*을 선택한 다음, *플러그인 세부 정보* 섹션에서 서비스 옵션의 선택을 취소하여 플러그인을 비활성화합니다.
. VMware vSphere에 로그인합니다.
. 왼쪽 탐색기 화면에서 SnapCenter Plug-in for VMware vSphere 인스턴스를 마우스 오른쪽 버튼으로 클릭합니다(이름 `.tar` 가상 어플라이언스를 배포할 때 사용된 파일)을 선택하고 *디스크에서 삭제*를 선택합니다.
. 애플리케이션 일관성 백업을 위해 다른 SnapCenter 플러그인을 지원하기 위해 SnapCenter Plug-in for VMware vSphere 사용한 경우 SnapCenter 에 로그인하고 vSphere 호스트를 제거합니다.


.당신이 완료한 후
가상 어플라이언스는 여전히 배포되어 있지만 SnapCenter Plug-in for VMware vSphere 제거되었습니다.

SnapCenter Plug-in for VMware vSphere 의 호스트 VM을 제거한 후에도 로컬 vCenter 캐시가 새로 고쳐질 때까지 해당 플러그인이 vCenter에 나열되어 있을 수 있습니다.  하지만 플러그인이 제거되었기 때문에 해당 호스트에서 SnapCenter VMware vSphere 작업을 수행할 수 없습니다.  로컬 vCenter 캐시를 새로 고치려면 먼저 SnapCenter Plug-in for VMware vSphere 구성 페이지에서 어플라이언스가 비활성화 상태인지 확인한 다음 vCenter 웹 클라이언트 서비스를 다시 시작합니다.
