---
sidebar: sidebar 
permalink: scpivs44_predefined_roles_packaged_with_snapcenter.html 
keywords:  
summary: vCenter Server RBAC 작업을 간소화하기 위해 SnapCenter Plug-in for VMware vSphere 사용자가 SnapCenter 작업을 수행할 수 있도록 하는 미리 정의된 역할 세트를 제공합니다.  사용자가 SnapCenter 정보를 볼 수 있지만 어떤 작업도 수행할 수 없는 읽기 전용 역할도 있습니다. 
---
= SnapCenter Plug-in for VMware vSphere 과 함께 제공되는 미리 정의된 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter Server RBAC 작업을 간소화하기 위해 SnapCenter Plug-in for VMware vSphere 사용자가 SnapCenter 작업을 수행할 수 있도록 하는 미리 정의된 역할 세트를 제공합니다.  사용자가 SnapCenter 정보를 볼 수 있지만 어떤 작업도 수행할 수 없는 읽기 전용 역할도 있습니다.

미리 정의된 역할에는 SnapCenter 관련 필수 권한과 기본 vCenter Server 권한이 모두 있어 작업이 올바르게 완료되도록 보장합니다.  또한, 역할은 지원되는 모든 vCenter Server 버전에서 필요한 권한을 갖도록 설정됩니다.

관리자는 이러한 역할을 적절한 사용자에게 할당할 수 있습니다.

SnapCenter Plug-in for VMware vSphere vCenter 웹 클라이언트 서비스를 다시 시작하거나 설치를 수정할 때마다 이러한 역할을 기본값(초기 권한 집합)으로 되돌립니다.  SnapCenter Plug-in for VMware vSphere 업그레이드하면 미리 정의된 역할이 해당 플러그인 버전에서 작동하도록 자동으로 업그레이드됩니다.

다음 표에 표시된 대로 *메뉴 > 관리 > 역할*을 선택하면 vCenter GUI에서 미리 정의된 역할을 볼 수 있습니다.

|===
| 역할 | 설명 


| SCV 관리자 | SnapCenter Plug-in for VMware vSphere 작업을 모두 수행하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter 관련 권한을 제공합니다.  SCV 6.1 릴리스부터 이 역할에 2차 보호를 생성하는 새로운 권한이 추가되었습니다. 


| SCV 백업 | vSphere 개체(가상 머신 및 데이터 저장소)를 백업하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter 관련 권한을 제공합니다.  사용자는 구성 권한도 가질 수 있습니다.  사용자는 백업을 복원할 수 없습니다.  SCV 6.1 릴리스부터 이 역할에 2차 보호를 생성하는 새로운 권한이 추가되었습니다. 


| SCV 게스트 파일 복원 | 게스트 파일과 폴더를 복원하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter 관련 권한을 제공합니다.  사용자는 VM이나 VMDK를 복원할 수 없습니다. 


| SCV 복원 | SnapCenter Plug-in for VMware vSphere 사용하여 백업된 vSphere 개체를 복원하고 게스트 파일과 폴더를 복원하는 데 필요한 모든 기본 vCenter Server 및 SnapCenter 관련 권한을 제공합니다.  사용자는 구성 권한도 가질 수 있습니다.  사용자는 vSphere 개체를 백업할 수 없습니다. 


| SCV 뷰 | SnapCenter Plug-in for VMware vSphere 모든 백업, 리소스 그룹 및 정책에 대한 읽기 전용 액세스를 제공합니다. 
|===