---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: vSphere 클라이언트 대시보드에서 상태 정보를 볼 수 있습니다.  상태 정보는 1시간마다 업데이트됩니다. 
---
= 상태 정보 보기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vSphere 클라이언트 대시보드에서 상태 정보를 볼 수 있습니다.  상태 정보는 1시간마다 업데이트됩니다.

.단계
. vCenter 클라이언트 바로 가기 페이지에서 SnapCenter Plug-in for VMware vSphere (SCV)을 선택합니다.
. SCV의 왼쪽 탐색 창에서 *대시보드* > *상태*를 선택합니다.
. 다음 표에 나열된 대로 개요 상태 정보를 보거나 자세한 내용을 보려면 링크를 선택하세요.
+
|===
| 이 대시보드 타일은… | 다음 정보가 표시됩니다… 


 a| 
최근 직업 활동
 a| 
가장 최근의 백업, 복원 및 마운트 작업 3~5개입니다.

** 해당 직무에 대한 자세한 내용을 보려면 직무 ID를 선택하세요.
** 모든 작업에 대한 자세한 내용을 보려면 *모두 보기*를 선택하세요. 작업 모니터 탭으로 이동합니다.




 a| 
일자리
 a| 
선택한 기간 내에 수행된 각 작업 유형(백업, 복원, 마운트)의 수입니다.  차트의 특정 섹션 위에 커서를 올려 놓으면 해당 카테고리에 대한 자세한 내용을 볼 수 있습니다.



 a| 
최신 보호 요약
 a| 
선택한 기간 내에 기본 및 보조 VM 또는 데이터 저장소의 데이터 보호 상태 요약입니다.

** 드롭다운 메뉴를 선택하여 *VM* 또는 *데이터 저장소*를 선택하세요.
** 보조 저장소의 경우 * SnapVault* 또는 * SnapMirror*를 선택하세요.
** 차트의 특정 섹션 위에 커서를 올려 놓으면 해당 카테고리에 속한 VM 또는 데이터스토어의 수를 확인할 수 있습니다.  성공 카테고리에는 각 리소스에 대한 가장 최근 백업이 나열됩니다.
** 구성 파일을 편집하여 시간 창을 변경할 수 있습니다.  기본값은 7일입니다. 자세한 내용은 다음을 참조하세요. link:scpivs44_customize_your_configuration.html["구성을 사용자 정의하세요"] .
** 내부 카운터는 1차 또는 2차 백업이 끝날 때마다 업데이트됩니다.  대시보드 타일은 6시간마다 새로 고쳐집니다.  새로 고침 시간을 변경할 수 없습니다.  참고: 미러 볼트 보호 정책을 사용하는 경우 보호 요약에 대한 카운터는 SnapVault 차트가 아닌 SnapMirror 요약 차트에 표시됩니다.




 a| 
구성
 a| 
SnapCenter Plug-in for VMware vSphere 관리하는 각 유형의 개체의 총 수입니다.



 a| 
스토리지
 a| 
생성된 스냅샷, SnapVault 및 SnapMirror 스냅샷의 총 수와 기본 및 보조 스냅샷에 사용된 저장 용량입니다. 선형 그래프는 90일 동안의 일별 1차 및 2차 저장소 소비량을 별도로 표시합니다.  저장소 정보는 24시간마다 오전 1시 8분에 업데이트됩니다. 저장소 절약량은 논리적 용량(스냅샷 절약량과 사용된 저장소 용량)을 기본 저장소의 물리적 용량으로 나눈 비율입니다.  막대 그래프는 저장 공간 절약 효과를 보여줍니다.

차트의 선 위에 커서를 올려 놓으면 일별 자세한 결과를 볼 수 있습니다.

|===

