---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vmdks.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere 사용하여 VMDK에 대한 복원 작업을 수행하려면 규정된 REST API 호출 순서를 따라야 합니다. 
---
= VMDK를 복원하기 위한 REST API 워크플로
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere 사용하여 VMDK에 대한 복원 작업을 수행하려면 규정된 REST API 호출 순서를 따라야 합니다.

각 REST API에 대해 다음을 추가합니다. `\https://<server>:<port>` REST API의 전면에 위치하여 완전한 엔드포인트를 형성합니다.

|===
| 단계 | REST API | 댓글 


| 1 | 로 가다 `\http://<vCenter-IP>/mob` | 자세한 내용은 VMware Managed Objects URL에서 확인하세요.  VMDK가 위치한 VM에 대한 *moref*를 참고하세요. 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups`지정된 VM에 대한 백업 목록을 가져옵니다.  1단계의 *moref*를 전달하세요.  복원하려는 백업의 *backupId*를 기록해 두세요. 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations`지정된 백업에 대한 스냅샷의 위치를 가져옵니다.  2단계의 *backupId*를 전달합니다.  *snapshotLocationsList* 정보를 참고하세요. 


| 4 | `/4.1/vm/{moref}/backups/
vmdklocations` | `Get Vmdk Locations`지정된 VM에 대한 VMDK 목록을 가져옵니다.  *vmdkLocationsList* 정보를 참고하세요. 


| 5 | `/4.1/vm/{ moref}/backups/
{backupId}/
availabledatastores` | `Get Available Datastores`복원 작업에 사용할 수 있는 데이터 저장소 목록을 가져옵니다.  1단계의 *moref*를 전달하세요.  2단계의 *backupId*를 전달합니다.  *DatastoreNameList* 정보를 참고하세요. 


| 6 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts`백업이 저장된 호스트에 대한 정보를 가져옵니다.  1단계의 *moref*를 전달하세요.  *availableEsxHostsList* 정보를 확인하세요. 


| 7 | `/4.1/vm/{moref}/backups/
{backupId}/restorevmdks`  a| 
`Restore a VMDK from a backup`지정된 백업에서 지정된 VMDK를 복원합니다.  *esxHost* 속성에서 6단계의 *availableEsxHostsList*에서 정보를 전달합니다.  3단계부터 5단계까지의 정보를 *vmdkRestoreLocations* 속성에 전달합니다.

* restoreFromLocation 속성에서 3단계의 snapshotLocationsList에서 정보를 전달합니다.
* vmdkToRestore 속성에서 4단계의 vmdkLocationsList의 정보를 전달합니다.
* restoreToDatastore 속성에서 5단계의 DatastoreNameList의 정보를 전달합니다.


|===