---
sidebar: sidebar 
permalink: scpivs44_register_snapcenter_plugin_vmware_vsphere_with_snapcenter_server.html 
keywords:  
summary: 'SnapCenter 에서 VMDK 기반 애플리케이션 워크플로(가상화된 데이터베이스 및 파일 시스템을 위한 애플리케이션 기반 보호 워크플로)를 수행하려면 SnapCenter 서버에 SnapCenter Plug-in for VMware vSphere 등록해야 합니다.' 
---
= SnapCenter 서버 SnapCenter Plug-in for VMware vSphere 등록
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter 에서 VMDK 기반 애플리케이션 워크플로(가상화된 데이터베이스 및 파일 시스템을 위한 애플리케이션 기반 보호 워크플로)를 수행하려면 SnapCenter 서버에 SnapCenter Plug-in for VMware vSphere 등록해야 합니다.

SnapCenter 사용자이고 SnapCenter 4.2로 업그레이드하고 VMDK 백업을 VMware용 SnapCenter 플러그인으로 마이그레이션한 경우, 마이그레이션 명령은 자동으로 플러그인을 등록합니다.

.시작하기 전에
* SnapCenter Server 4.2 이상을 실행해야 합니다.
* SnapCenter Plug-in for VMware vSphere 배포하고 활성화해야 합니다.


.이 작업에 관하여
* SnapCenter GUI를 사용하여 "vsphere" 유형 호스트를 추가하여 SnapCenter Server에 SnapCenter Plug-in for VMware vSphere 등록합니다.
+
포트 8144는 SnapCenter Plug-in for VMware vSphere 내 통신을 위해 미리 정의되어 있습니다.

+
동일한 SnapCenter Server 4.2에서 SnapCenter Plug-in for VMware vSphere 의 여러 인스턴스를 등록하여 VM에서 애플리케이션 기반 데이터 보호 작업을 지원할 수 있습니다.  여러 SnapCenter 서버에 동일한 SnapCenter Plug-in for VMware vSphere 등록할 수 없습니다.

* 연결 모드의 vCenter의 경우 각 vCenter에 대해 SnapCenter Plug-in for VMware vSphere 등록해야 합니다.


.단계
. SnapCenter GUI 왼쪽 탐색 창에서 *호스트*를 선택합니다.
. 상단에서 *관리되는 호스트* 탭이 선택되어 있는지 확인한 다음, 가상 어플라이언스 호스트 이름을 찾아 SnapCenter 서버에서 확인되는지 확인합니다.
. 마법사를 시작하려면 *추가*를 선택하세요.
. *호스트 추가* 대화 상자에서 다음 표에 나열된 대로 SnapCenter 서버에 추가할 호스트를 지정합니다.
+
|===
| 이 분야에서는… | 이렇게 하세요… 


| 호스트 유형 | 호스트 유형으로 *vSphere*를 선택합니다. 


| 호스트 이름 | 가상 어플라이언스의 IP 주소를 확인하세요. 


| 신임장 | 배포 중에 제공된 SnapCenter Plug-in for VMware vSphere 의 사용자 이름과 비밀번호를 입력하세요. 
|===
. *제출*을 선택하세요.
+
VM 호스트가 성공적으로 추가되면 관리 호스트 탭에 표시됩니다.

. 왼쪽 탐색 창에서 *설정*을 선택한 다음 *자격 증명* 탭을 선택하고 *추가*를 선택하여 가상 어플라이언스에 대한 자격 증명을 추가합니다.
. SnapCenter Plug-in for VMware vSphere 배포 중에 지정된 자격 증명 정보를 제공합니다.
+

NOTE: 인증 필드에서는 Linux를 선택해야 합니다.



.당신이 완료한 후
SnapCenter Plug-in for VMware vSphere 자격 증명이 수정된 경우 SnapCenter 관리 호스트 페이지를 사용하여 SnapCenter 서버에서 등록을 업데이트해야 합니다.
