---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere 대한 백업 정책을 만들고, 수정하고, 보고, 분리하고, 삭제할 수 있습니다.  데이터 보호 작업을 수행하려면 정책이 필요합니다. 
---
= 정책 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere 대한 백업 정책을 만들고, 수정하고, 보고, 분리하고, 삭제할 수 있습니다.  데이터 보호 작업을 수행하려면 정책이 필요합니다.



[[detach-policies]]
== 정책 분리

더 이상 해당 정책으로 리소스의 데이터 보호를 관리하지 않으려면 SnapCenter Plug-in for VMware vSphere 에서 정책을 분리할 수 있습니다.  정책을 제거하거나 일정 빈도를 수정하려면 먼저 정책을 분리해야 합니다.

.이 작업에 관하여
SnapCenter Plug-in for VMware vSphere 에서 정책을 분리하기 위한 지침은 SnapCenter 리소스 그룹에 대한 지침과 다릅니다.  VMware vSphere 클라이언트 리소스 그룹의 경우 모든 정책을 분리할 수 있으며, 그렇게 하면 리소스 그룹에 정책이 없게 됩니다.  하지만 해당 리소스 그룹에서 데이터 보호 작업을 수행하려면 최소한 하나의 정책을 첨부해야 합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *리소스 그룹*을 선택한 다음, 리소스 그룹을 선택하고 *편집*을 선택합니다.
. *리소스 그룹 편집* 마법사의 *정책* 페이지에서 분리하려는 정책 옆에 있는 확인 표시를 지웁니다.
+
정책을 확인하여 리소스 그룹에 정책을 추가할 수도 있습니다.

. 마법사의 나머지 부분에서 리소스 그룹에 대한 추가 수정을 한 다음 *마침*을 선택합니다.




[[modify-policies]]
== 정책 수정

SnapCenter Plug-in for VMware vSphere 의 정책을 수정할 수 있습니다.  정책이 리소스 그룹에 연결되어 있는 동안 빈도, 복제 옵션, 스냅샷 보존 설정 또는 스크립트 정보를 수정할 수 있습니다.

.이 작업에 관하여
SnapCenter Plug-in for VMware vSphere 수정하는 것은 SnapCenter 애플리케이션 기반 플러그인에 대한 백업 정책을 수정하는 것과 다릅니다.  플러그인 정책을 수정할 때 리소스 그룹에서 정책을 분리할 필요가 없습니다.

복제 또는 보존 설정을 수정하기 전에 발생할 수 있는 결과를 고려해야 합니다.

* 복제 또는 보존 설정 증가
+
백업은 새로운 설정에 도달할 때까지 계속 누적됩니다.

* 복제 또는 보존 설정 감소
+
다음 백업을 수행하면 새로운 설정을 초과하는 백업은 삭제됩니다.




NOTE: SnapCenter Plug-in for VMware vSphere 수정하려면 플러그인 리소스 그룹에서 일정을 수정해야 합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *정책*을 선택한 다음, 정책을 선택하고 *편집*을 선택합니다.
. 정책 필드를 수정합니다.
. 완료되면 *업데이트*를 선택하세요.


변경 사항은 다음에 예약된 백업이 수행될 때 적용됩니다.



[[delete-policies]]
== 정책 삭제

SnapCenter Plug-in for VMware vSphere 대해 구성된 백업 정책이 더 이상 필요하지 않은 경우 이를 삭제하는 것이 좋습니다.

.시작하기 전에
SnapCenter 의 가상 어플라이언스에 있는 모든 리소스 그룹에서 정책을 분리해야만 정책을 삭제할 수 있습니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *정책*을 선택한 다음, 정책을 선택하고 *제거*를 선택합니다.
. 확인 대화 상자에서 *확인*을 선택합니다.

