---
sidebar: sidebar 
permalink: scpivs44_set_up_proxy_vms_for_restore_operations.html 
keywords:  
summary: 게스트 파일 복원 작업을 위해 가상 디스크를 연결하기 위해 프록시 VM을 사용하려면 복원 작업을 시작하기 전에 프록시 VM을 설정해야 합니다.  언제든지 프록시 VM을 설정할 수 있지만 플러그인 배포가 완료된 직후에 설정하는 것이 더 편리할 수 있습니다. 
---
= 복원 작업을 위한 프록시 VM 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
게스트 파일 복원 작업을 위해 가상 디스크를 연결하기 위해 프록시 VM을 사용하려면 복원 작업을 시작하기 전에 프록시 VM을 설정해야 합니다.  언제든지 프록시 VM을 설정할 수 있지만 플러그인 배포가 완료된 직후에 설정하는 것이 더 편리할 수 있습니다.

.단계
. vSphere 클라이언트 바로 가기 창에서 플러그인 아래에 있는 * SnapCenter Plug-in for VMware vSphere*을 선택합니다.
. 왼쪽 탐색창에서 *게스트 파일 복원*을 선택하세요.
. *자격 증명으로 실행* 섹션에서 다음 중 하나를 수행합니다.
+
|===
| 이렇게 하려면… | 이렇게 하세요… 


| 기존 자격 증명을 사용하세요 | 구성된 자격 증명 중 하나를 선택하세요. 


| 새로운 자격 증명 추가  a| 
.. *추가*를 선택하세요.
.. *자격 증명으로 실행* 대화 상자에서 자격 증명을 입력합니다.
.. *VM 선택*을 선택한 다음, *프록시 VM* 대화 상자에서 VM을 선택합니다.  *저장*을 선택하여 *자격 증명으로 실행* 대화 상자로 돌아갑니다.
.. 자격 증명을 입력하세요. 사용자 이름에는 "관리자"를 입력해야 합니다.


|===
+
SnapCenter Plug-in for VMware vSphere 선택된 자격 증명을 사용하여 선택된 프록시 VM에 로그인합니다.

+
실행 자격 증명은 Windows에서 제공하는 기본 도메인 관리자 또는 기본 제공 로컬 관리자여야 합니다.  작업 그룹 사용자는 기본 제공 로컬 관리자 계정을 사용할 수 있습니다.

. *프록시 자격 증명* 섹션에서 *추가*를 선택하여 프록시로 사용할 VM을 추가합니다.
. *프록시 VM* 대화 상자에서 정보를 입력한 다음 *저장*을 선택합니다.



NOTE: ESXi 호스트에서 삭제하려면 먼저 SnapCenter Plug-in for VMware vSphere 에서 프록시 VM을 삭제해야 합니다.
