---
sidebar: sidebar 
permalink: scpivs44_guest_file_restore_scenarios_you_might_encounter.html 
keywords:  
summary: 게스트 파일을 복원하려고 할 때 게스트 파일 복원 세션이 비어 있거나, 게스트 파일 복원 디스크 연결 작업이 실패하거나, 게스트 파일 복원 세션이 중단된 후 백업이 분리되지 않는 경우가 발생할 수 있습니다. 
---
= 게스트 파일 복원 시나리오 발생 가능성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
게스트 파일을 복원하려고 할 때 다음과 같은 시나리오가 발생할 수 있습니다.



== 게스트 파일 복원 세션이 비어 있습니다.

이 문제는 게스트 파일 복원 세션을 생성하고 해당 세션이 활성화되어 있는 동안 게스트 운영 체제가 재부팅되는 경우 발생합니다.  이런 경우 게스트 OS의 VMDK가 오프라인 상태로 유지될 수 있습니다.  따라서 게스트 파일 복구 세션을 탐색하려고 하면 목록이 비어 있습니다.

이 문제를 해결하려면 게스트 OS에서 VMDK를 수동으로 다시 온라인으로 전환하세요.  VMDK가 온라인 상태이면 게스트 파일 복원 세션에 올바른 내용이 표시됩니다.



== 게스트 파일 복원 디스크 연결 작업이 실패했습니다.

이 문제는 게스트 파일 복원 작업을 시작했지만 VMware 도구가 실행 중이고 게스트 OS 자격 증명이 올바른 경우에도 디스크 연결 작업이 실패할 때 발생합니다.  이런 경우, 다음 오류가 반환됩니다.

`Error while validating guest credentials, failed to access guest system using specified credentials: Verify VMWare tools is running properly on system and account used is Administrator account, Error is SystemError vix error codes = (3016, 0).`

이 문제를 해결하려면 게스트 OS에서 VMware Tools Windows 서비스를 다시 시작한 다음 게스트 파일 복원 작업을 다시 시도하세요.



== 게스트 이메일은 파일 이름에 ??????가 표시됩니다.

이 문제는 게스트 파일 복원 기능을 사용하여 이름에 영어가 아닌 문자가 포함된 파일이나 폴더를 복원하고 이메일 알림에 복원된 파일 이름에 대한 "??????"가 표시되는 경우 발생합니다.  이메일 첨부 파일에는 복구된 파일과 폴더의 이름이 올바르게 나열되어 있습니다.



== 게스트 파일 복원 세션이 중단된 후에도 백업이 분리되지 않습니다.

이 문제는 VM 일치 백업에서 게스트 파일 복원 작업을 수행할 때 발생합니다.  게스트 파일 복원 세션이 활성화되어 있는 동안 동일한 VM에 대해 또 다른 VM 일치 백업이 수행됩니다.  게스트 파일 복원 세션이 24시간 후 수동 또는 자동으로 연결이 끊어지면 해당 세션의 백업은 분리되지 않습니다.

이 문제를 해결하려면 활성 게스트 파일 복원 세션에서 연결된 VMDK를 수동으로 분리하세요.
