---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere 사용하여 VM과 데이터 저장소를 백업하기 전에 백업 정책을 만들어야 합니다. 
---
= VM 및 데이터 저장소에 대한 백업 정책 생성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere 사용하여 VM과 데이터 저장소를 백업하기 전에 백업 정책을 만들어야 합니다.

.시작하기 전에
* 필수 조건을 읽어 보셨을 겁니다.
* 보조 저장소 관계가 구성되어 있어야 합니다.
+
** 스냅샷을 미러 또는 볼트 보조 저장소에 복제하는 경우 관계를 구성해야 하며 SnapCenter 관리자가 소스 및 대상 볼륨 모두에 대한 저장소 VM을 할당해야 합니다.
** NFS 또는 VMFS 데이터 저장소에서 Version-FlexibleMirror 관계에 대한 스냅샷을 보조 저장소로 성공적으로 전송하려면 SnapMirror 정책 유형이 비동기 미러이고 "all_source_snapshots" 옵션이 선택되어 있는지 확인하세요.
** 보조 저장소(미러 볼트)의 스냅샷 수가 최대 한도에 도달하면 백업 작업에서 백업을 등록하고 보존을 적용하는 활동이 다음 오류와 함께 실패합니다. `This snapshot is currently used as a reference snapshot by one or more SnapMirror relationships. Deleting the snapshot can cause future SnapMirror operations to fail.`
+
이 문제를 해결하려면 보조 저장소에 대한 SnapMirror 보존 정책을 구성하여 스냅샷의 최대 한도에 도달하지 않도록 합니다.

+
관리자가 사용자에게 리소스를 할당하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/snapcenter/get-started/rbac-snapcenter.html["역할 기반 액세스 제어 사용에 대한 SnapCenter 정보"^] .



* VM 일관성 백업을 원하면 VMware 도구를 설치하고 실행해야 합니다.  VM을 정지시키려면 VMware 도구가 필요합니다.  vVol VM에서는 VM 일관성 백업이 지원되지 않습니다.
* SnapMirror 액티브 동기화를 사용하면 사이트 전체에 장애가 발생하더라도 비즈니스 서비스가 계속 운영될 수 있으며, 보조 복사본을 사용하여 애플리케이션이 투명하게 장애 조치되도록 지원합니다.
+

NOTE: SnapMirror Active Sync는 VMFS 데이터스토어에서만 지원됩니다.

+
SnapMirror 활성 동기화 배포에서 VMFS 데이터 저장소를 보호하려면 SnapCenter 관리자가 다음을 수행해야 합니다.

+
** 기술 보고서에 설명된 대로 클러스터와 중재자를 구성합니다. https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/mediator-install-task.html["SnapMirror 활성 동기화를 위해 ONTAP Mediator 및 클러스터 구성"] .
** VMFS 데이터 저장소와 연결된 볼륨을 일관성 그룹에 추가하고 두 ONTAP 스토리지 시스템 간에 _AutomatedFailOver_ 또는 _AutomatedFailOverDuplex_ 보호 정책을 사용하여 데이터 보호 관계를 만듭니다.  _AutomatedFailOverDuplex_ 정책은 ONTAP 9.15.1 릴리스부터 지원됩니다.





NOTE: 팬아웃 구성에서는 3차 사이트에 대한 일관성 그룹이 지원되지 않습니다.

.이 작업에 관하여
이 마법사 페이지의 대부분 필드는 설명이 필요 없습니다. 다음 정보는 귀하에게 지침이 필요할 수 있는 몇몇 분야에 대해 설명합니다.

.단계
. SCV 플러그인의 왼쪽 탐색 창에서 *정책*을 선택합니다.
. *정책* 페이지에서 *만들기*를 선택하여 마법사를 시작합니다.
. *새 백업 정책* 페이지에서 정책 이름과 설명을 입력합니다.
+
** 연결 모드
+
연결 모드에서는 각 vCenter에 별도의 가상 어플라이언스가 있습니다. 따라서 vCenter 전체에서 중복된 이름을 사용할 수 있습니다.  하지만 리소스 그룹과 동일한 vCenter에 정책을 만들어야 합니다.

** 지원되지 않는 문자
+
VM, 데이터 저장소, 클러스터, 정책, 백업 또는 리소스 그룹 이름에는 다음 특수 문자를 사용하지 마세요: % & * $ # @ ! \ / : * ? " < > - | ; ' , 그리고 공백.

+
밑줄 문자(_)가 허용됩니다.



. 주파수 설정을 지정합니다.
+
정책은 백업 빈도만 지정합니다. 백업을 위한 구체적인 보호 일정은 리소스 그룹에서 정의됩니다. 따라서 두 개 이상의 리소스 그룹이 동일한 정책과 백업 빈도를 공유할 수 있지만 백업 일정은 서로 다를 수 있습니다.

. 스냅샷 잠금을 활성화하려면 *잠금 기간* 확인란을 선택하세요.  기본 및 보조 스냅샷 잠금 기간을 일/월/년으로 선택할 수 있습니다.
+

NOTE: ONTAP SnapMirror 정책에 설정된 보존 값에 관계없이, 보조 스냅샷 복사본은 지정된 보조 스냅샷 잠금 기간 이전에는 삭제되지 않습니다.

. 보존 설정을 지정합니다.
+

IMPORTANT: SnapVault 복제를 활성화하려면 보존 횟수를 2개 이상의 백업으로 설정해야 합니다.  보존 횟수를 1로 설정하면 보존 작업이 실패할 수 있습니다.  이는 첫 번째 스냅샷이 새 스냅샷이 대상에 복제될 때까지 SnapVault 관계에 대한 참조 스냅샷이기 때문입니다.

+

NOTE: 최대 보존 값은 1018개의 백업입니다. 보존 기간이 기본 ONTAP 버전에서 지원하는 것보다 높은 값으로 설정된 경우 백업이 실패합니다.  이는 데이터 저장소를 확장하는 경우에도 마찬가지입니다.



. *복제* 필드에서 다음 표에 표시된 대로 보조 저장소에 대한 복제 유형을 지정합니다.
+
|===
| 이 분야에서는… | 이렇게 하세요… 


| 백업 후 SnapMirror 업데이트  a| 
기본 백업 볼륨과 SnapMirror 관계가 있는 다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 옵션을 선택합니다.  볼륨이 미러-볼트 관계로 구성된 경우 백업을 미러-볼트 대상에 복사하려면 *백업 후 SnapVault 업데이트* 옵션만 선택해야 합니다.


NOTE: 이 옵션은 SnapCenter Plug-in for VMware vSphere FlexGroup 볼륨에 있는 데이터스토어에서 지원됩니다.


NOTE: SnapMirror 활성 동기화 배포에서 VMFS 데이터 저장소를 보호하려면 _시작하기 전에_ 섹션에 언급된 전제 조건을 완료하고 *백업 후 SnapMirror 업데이트*를 활성화해야 합니다.



| 백업 후 SnapVault 업데이트  a| 
기본 백업 볼륨과 SnapVault 관계가 있는 다른 볼륨에서 디스크 간 백업 복제를 수행하려면 이 옵션을 선택합니다.


IMPORTANT: 볼륨이 미러-볼트 관계로 구성된 경우 백업을 미러-볼트 대상으로 복사하려면 이 옵션만 선택해야 합니다.


NOTE: 이 옵션은 SnapCenter Plug-in for VMware vSphere FlexGroup 볼륨에 있는 데이터스토어에서 지원됩니다.



| 스냅샷 라벨  a| 
이 정책으로 생성된 SnapVault 및 SnapMirror 스냅샷에 추가할 선택 사항인 사용자 지정 레이블을 입력합니다.  스냅샷 레이블은 이 정책으로 생성된 스냅샷을 보조 저장소 시스템의 다른 스냅샷과 구별하는 데 도움이 됩니다.


NOTE: 스냅샷 레이블에는 최대 31자가 허용됩니다.

|===
. 선택 사항: *고급* 필드에서 필요한 필드를 선택합니다.  고급 필드 세부 정보는 다음 표에 나와 있습니다.
+
|===
| 이 분야에서는… | 이렇게 하세요… 


| VM 일관성  a| 
백업 작업이 실행될 때마다 VM을 정지하고 VMware 스냅샷을 생성하려면 이 상자를 선택하세요.

이 옵션은 vVols 에서는 지원되지 않습니다.  vVol VM의 경우 충돌 일관성 백업만 수행됩니다.


IMPORTANT: VM 일관성 백업을 수행하려면 VM에서 VMware 도구를 실행해야 합니다.  VMware 도구가 실행 중이 아니면 대신 충돌 일관성 백업이 수행됩니다.


NOTE: VM 일관성 상자를 선택하면 백업 작업에 더 오랜 시간이 걸리고 더 많은 저장 공간이 필요할 수 있습니다.  이 시나리오에서는 VM이 ​​먼저 정지된 다음 VMware가 VM 일관성 스냅샷을 수행하고 SnapCenter 백업 작업을 수행한 후 VM 작업이 재개됩니다.  VM 게스트 메모리는 VM 일관성 스냅샷에 포함되지 않습니다.



| 독립 디스크가 있는 데이터 저장소 포함 | 임시 데이터가 들어 있는 독립 디스크가 있는 모든 데이터 저장소를 백업에 포함하려면 이 상자를 선택하세요. 


| 스크립트  a| 
SnapCenter Plug-in for VMware vSphere 백업 작업 전이나 후에 실행되기를 원하는 사전 스크립트 또는 사후 스크립트의 완전한 경로를 입력하세요. 예를 들어, SNMP 트랩을 업데이트하고, 알림을 자동화하고, 로그를 보내는 스크립트를 실행할 수 있습니다.  스크립트 경로는 스크립트가 실행될 때 검증됩니다.


NOTE: 사전 스크립트와 사후 스크립트는 가상 어플라이언스 VM에 있어야 합니다.  여러 스크립트를 입력하려면 각 스크립트 경로 뒤에 *Enter*를 눌러 각 스크립트를 별도의 줄에 나열합니다.  문자 ";"은 허용되지 않습니다.

|===
. *추가*를 선택하세요.
+
정책 페이지에서 정책을 선택하면 정책이 생성되었는지 확인하고 정책 구성을 검토할 수 있습니다.


