---
sidebar: sidebar 
permalink: scpivs44_download_job_logs.html 
keywords:  
summary: SnapCenter VMware vSphere 클라이언트 대시보드의 작업 모니터 탭에서 작업 로그를 다운로드할 수 있습니다. 
---
= 작업 로그 다운로드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter VMware vSphere 클라이언트 대시보드의 작업 모니터 탭에서 작업 로그를 다운로드할 수 있습니다.

VMware vSphere 클라이언트를 사용하는 동안 예기치 않은 동작이 발생하면 로그 파일을 사용하여 원인을 파악하고 문제를 해결할 수 있습니다.


NOTE: 작업 로그를 보존하는 기본값은 30일이고, 작업을 보존하는 기본값은 90일입니다.  구성된 보존 기간보다 오래된 작업 로그와 작업은 6시간마다 삭제됩니다.  구성을 사용할 수 있습니다 `jobs/cleanup` 작업 및 작업 로그를 보관하는 기간을 수정하는 REST API입니다.  삭제 일정을 수정할 수 없습니다.

.단계
. vCenter 클라이언트 바로 가기 페이지에서 SnapCenter Plug-in for VMware vSphere (SCV)을 선택합니다.
. SCV의 왼쪽 탐색 창에서 *대시보드* > *작업 모니터*를 선택합니다.
. 작업 모니터 제목 표시줄에서 다운로드 아이콘을 선택합니다.
+
아이콘을 보려면 오른쪽으로 스크롤해야 할 수도 있습니다.

+
작업을 두 번 클릭하여 작업 세부 정보 창에 접근한 다음 *작업 로그 다운로드*를 선택할 수도 있습니다.



.결과
작업 로그는 SnapCenter Plug-in for VMware vSphere 배포된 Linux VM 호스트에 있습니다.  기본 작업 로그 위치는 다음과 같습니다. `/var/log/netapp` .

작업 로그를 다운로드하려고 했지만 오류 메시지에 명시된 로그 파일이 삭제된 경우 다음 오류가 발생할 수 있습니다. `HTTP ERROR 500 Problem accessing /export-scv-logs` .  이 오류를 해결하려면 오류 메시지에 명시된 파일의 파일 접근 상태와 권한을 확인하고 접근 문제를 해결하세요.
