---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 백업에 있는 파일에 액세스하려면 백업에서 기존 데이터 저장소를 마운트할 수 있습니다. 백업이 생성된 동일한 ESXi 호스트에 백업을 마운트하거나 동일한 유형의 VM 및 호스트 구성을 갖춘 대체 ESXi 호스트에 마운트할 수 있습니다. 호스트에 데이터 저장소를 여러 번 마운트할 수 있습니다. 
---
= 백업 마운트
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
백업에 있는 파일에 액세스하려면 백업에서 기존 데이터 저장소를 마운트할 수 있습니다. 백업이 생성된 동일한 ESXi 호스트에 백업을 마운트하거나 동일한 유형의 VM 및 호스트 구성을 갖춘 대체 ESXi 호스트에 마운트할 수 있습니다. 호스트에 데이터 저장소를 여러 번 마운트할 수 있습니다.

vVol 데이터스토어를 마운트할 수 없습니다.

.시작하기 전에
* 대체 ESXi 호스트가 스토리지에 연결할 수 있는지 확인하십시오.
+
대체 ESXi 호스트에 마운트하려면 대체 ESXi 호스트가 스토리지에 연결할 수 있고 다음 사항이 있는지 확인해야 합니다.

+
** 원래 호스트와 동일한 UID 및 GID
** SnapCenter Plug-in for VMware vSphere 의 경우 원래 호스트와 동일한 가상 어플라이언스


* iSCSI 프로토콜을 사용하는 경우 스토리지 시스템의 이니시에이터가 ESXi 호스트에 매핑되어 있는지 확인하세요.  NVMe 프로토콜을 사용하는 경우 필요한 하위 시스템을 ESXi 호스트에 매핑하기 위해 컨트롤러를 추가합니다.
* 오래된 LUN/네임스페이스 정리
+
ESXi 호스트는 데이터스토어당 고유한 LUN/네임스페이스를 하나만 검색할 수 있으므로, 두 개 이상을 찾으면 작업이 실패합니다.  이는 이전 마운트 작업이 완료되기 전에 마운트 작업을 시작하거나, LUN/네임스페이스를 수동으로 복제하거나, 마운트 해제 작업 중에 복제본이 저장소에서 삭제되지 않은 경우 발생할 수 있습니다.  여러 개의 복제본이 발견되는 것을 방지하려면 스토리지에서 모든 오래된 LUN/네임스페이스를 정리해야 합니다.



.이 작업에 관하여
데이터 저장소가 있는 FabricPool 의 스토리지 계층을 사용할 수 없는 경우 마운트 작업이 실패할 수 있습니다.

.단계
. VMware vSphere 클라이언트 바로가기 페이지에서 *저장소*를 선택합니다.
. 데이터스토어를 마우스 오른쪽 버튼으로 클릭하고 * SnapCenter Plug-in for VMware vSphere* > *백업 마운트*를 선택합니다.
. *데이터스토어 마운트* 페이지에서 백업과 백업 위치(기본 또는 보조)를 선택한 다음 *마침*을 선택합니다.
. 선택 사항: 데이터 저장소가 마운트되었는지 확인하려면 다음을 수행합니다.
+
.. 도구 모음에서 *메뉴*를 선택한 다음 드롭다운 목록에서 *저장소*를 선택합니다.
.. 왼쪽 탐색기 창에는 목록 맨 위에 마운트한 데이터 저장소가 표시됩니다.
+
볼륨을 복제할 때 새 스냅샷이 생성되는 것을 방지하려면 SnapVault 볼륨에 대한 ONTAP 일정을 끕니다.  기존의 스냅샷은 삭제되지 않습니다.




