---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: SnapCenter 데이터 보호 기능이 더 이상 필요하지 않으면 SnapCenter Plug-in for VMware vSphere 의 구성을 변경해야 합니다.  예를 들어, 테스트 환경에서 플러그인을 배포한 경우 해당 환경에서는 SnapCenter 기능을 비활성화하고 프로덕션 환경에서는 해당 기능을 활성화해야 할 수 있습니다. 
---
= SnapCenter Plug-in for VMware vSphere 비활성화 및 활성화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter 데이터 보호 기능이 더 이상 필요하지 않으면 SnapCenter Plug-in for VMware vSphere 의 구성을 변경해야 합니다.  예를 들어, 테스트 환경에서 플러그인을 배포한 경우 해당 환경에서는 SnapCenter 기능을 비활성화하고 프로덕션 환경에서는 해당 기능을 활성화해야 할 수 있습니다.

.시작하기 전에
* 관리자 권한이 있어야 합니다.
* SnapCenter 작업이 실행되고 있지 않은지 확인하세요.


.이 작업에 관하여
SnapCenter Plug-in for VMware vSphere 비활성화하면 모든 리소스 그룹이 일시 중단되고 플러그인이 vCenter에서 확장 프로그램으로 등록 취소됩니다.

SnapCenter Plug-in for VMware vSphere 활성화하면 플러그인이 vCenter에 확장 기능으로 등록되고, 모든 리소스 그룹이 프로덕션 모드가 되며, 모든 일정이 활성화됩니다.

.단계
. 선택 사항: 새로운 가상 어플라이언스에 복원하려는 경우 SnapCenter Plug-in for VMware vSphere 백업합니다.
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["SnapCenter Plug-in for VMware vSphere 백업"] .

. 다음 형식을 사용하여 SnapCenter Plug-in for VMware vSphere 에 로그인합니다. `\https://<OVA-IP-address>:8080` . 배포 시 설정한 관리자 사용자 이름과 비밀번호, 그리고 유지 관리 콘솔을 사용하여 생성된 MFA 토큰을 사용하여 로그인합니다.
+
SnapCenter Plug-in for VMware vSphere 의 IP 주소는 플러그인을 배포할 때 표시됩니다.

. 왼쪽 탐색 창에서 *구성*을 선택한 다음, *플러그인 세부 정보* 섹션에서 서비스 옵션의 선택을 취소하여 플러그인을 비활성화합니다.
. 선택을 확인하세요.
+
** SnapCenter Plug-in for VMware vSphere 만 사용하여 VM 일관성 백업을 수행한 경우
+
플러그인이 비활성화되어 더 이상 조치가 필요하지 않습니다.

** SnapCenter Plug-in for VMware vSphere 사용하여 애플리케이션 일관성 백업을 수행한 경우
+
플러그인이 비활성화되어 추가 정리가 필요합니다.

+
... VMware vSphere에 로그인합니다.
... VM의 전원을 끕니다.
... 왼쪽 탐색기 화면에서 SnapCenter Plug-in for VMware vSphere 인스턴스를 마우스 오른쪽 버튼으로 클릭합니다(이름 `.ova` 가상 어플라이언스를 배포할 때 사용된 파일)을 선택하고 *디스크에서 삭제*를 선택합니다.
... SnapCenter 에 로그인하고 vSphere 호스트를 제거합니다.





