---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: Windows 게스트 OS의 VMDK에서 하나 이상의 파일이나 폴더를 복원할 수 있습니다. 
---
= VMDK에서 게스트 파일 및 폴더 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 게스트 OS의 VMDK에서 하나 이상의 파일이나 폴더를 복원할 수 있습니다.

.이 작업에 관하여
기본적으로 연결된 가상 디스크는 24시간 동안 사용할 수 있으며 그 이후에는 자동으로 분리됩니다.  마법사에서 복원 작업이 완료되면 세션이 자동으로 삭제되도록 선택할 수도 있고, 언제든지 게스트 파일 복원 세션을 수동으로 삭제할 수도 있고, *게스트 구성* 페이지에서 시간을 연장할 수도 있습니다.

게스트 파일 또는 폴더 복원 성능은 두 가지 요인에 따라 달라집니다. 복원되는 파일 또는 폴더의 크기와 복원되는 파일 또는 폴더의 수입니다.  복원할 데이터 세트의 크기가 동일하다면, 다수의 작은 크기의 파일을 복원하는 데는 소수의 큰 크기의 파일을 복원하는 데에 비해 예상보다 더 오랜 시간이 걸릴 수 있습니다.


IMPORTANT: VM에서는 동시에 하나의 연결 또는 복원 작업만 실행할 수 있습니다.  동일한 VM에서 병렬 연결 또는 복원 작업을 실행할 수 없습니다.


IMPORTANT: 게스트 복원 기능을 사용하면 시스템 및 숨겨진 파일을 보고 복원하고 암호화된 파일을 볼 수 있습니다.  기존 시스템 파일을 덮어쓰거나 암호화된 파일을 암호화된 폴더로 복원하려고 시도하지 마세요.  복원 작업 동안 게스트 파일의 숨김, 시스템 및 암호화된 속성은 복원된 파일에 유지되지 않습니다.  예약된 파티션을 보거나 탐색하면 오류가 발생할 수 있습니다.

.단계
. vSphere 클라이언트 바로 가기 창에서 *호스트 및 클러스터*를 선택하고 VM을 선택합니다.
. VM을 마우스 오른쪽 버튼으로 클릭하고 * SnapCenter Plug-in for VMware vSphere* > *게스트 파일 복원*을 선택합니다.
. *복원 범위* 페이지에서 다음을 수행하여 연결하려는 가상 디스크가 포함된 백업을 지정합니다.
+
.. *백업 이름* 테이블에서 연결하려는 가상 디스크가 포함된 백업을 선택합니다.
.. *VMDK* 테이블에서 복원하려는 파일이나 폴더가 포함된 가상 디스크를 선택합니다.
.. *위치* 표에서 연결하려는 가상 디스크의 위치(기본 또는 보조)를 선택합니다.


. *손님 세부 정보* 페이지에서 다음을 수행하세요.
+
.. 가상 디스크를 연결할 위치를 선택하세요.
+
|===
| 이 옵션을 선택하세요… | 만약에… 


| 게스트 VM 사용  a| 
마법사를 시작하기 전에 마우스 오른쪽 버튼을 클릭한 VM에 가상 디스크를 연결한 다음, 마우스 오른쪽 버튼을 클릭한 VM에 대한 자격 증명을 선택합니다.


NOTE: VM에 대한 자격 증명이 이미 생성되어 있어야 합니다.



| 게스트 파일 복원 프록시 VM 사용  a| 
가상 디스크를 프록시 VM에 연결한 다음 프록시 VM을 선택합니다.


NOTE: 연결 및 복원 작업이 시작되기 전에 프록시 VM을 구성해야 합니다.

|===
.. *이메일 알림 보내기* 옵션을 선택하세요.
+
연결 작업이 완료되고 가상 디스크를 사용할 수 있게 되면 알림을 받으려면 이 옵션이 필요합니다.  알림 이메일에는 가상 디스크 이름, VM 이름, VMDK에 새로 할당된 드라이브 문자가 포함되어 있습니다.

+

TIP: 게스트 파일 복원은 비동기 작업이기 때문에 게스트 세션을 설정하는 데 시간 지연이 발생할 수 있으므로 이 옵션을 활성화하세요.

+
이 옵션은 vCenter에서 VMware vSphere 클라이언트를 설정할 때 구성된 이메일 설정을 사용합니다.



. 요약을 검토한 후 *마침*을 선택하세요.
+
*마침*을 선택하기 전에 마법사의 어느 페이지로든 돌아가서 정보를 변경할 수 있습니다.

. 첨부 작업이 완료될 때까지 기다리세요.
+
대시보드 작업 모니터에서 작업 진행 상황을 확인하거나 이메일 알림을 기다릴 수 있습니다.

. 연결된 가상 디스크에서 복원하려는 파일을 찾으려면 vSphere 클라이언트 바로 가기 창에서 * SnapCenter Plug-in for VMware vSphere*을 선택합니다.
. 왼쪽 탐색 창에서 *게스트 파일 복원* > *게스트 구성*을 선택합니다.
+
게스트 세션 모니터 테이블에서 *...를 선택하면 세션에 대한 추가 정보를 표시할 수 있습니다.  *오른쪽 열에.

. 알림 이메일에 나열된 가상 디스크에 대한 게스트 파일 복원 세션을 선택하세요.
+
시스템 예약 파티션을 포함하여 모든 파티션에 드라이브 문자가 지정됩니다.  VMDK에 여러 개의 파티션이 있는 경우 게스트 파일 찾아보기 페이지 상단의 드라이브 필드에서 드롭다운 목록에서 드라이브를 선택하여 특정 드라이브를 선택할 수 있습니다.

. 가상 디스크에 있는 파일과 폴더 목록을 보려면 *파일 찾아보기* 아이콘을 선택하세요.
+
폴더를 두 번 선택하여 찾아보고 개별 파일을 선택하면 파일 목록을 가져오는 동안 시간 지연이 발생할 수 있습니다. 이는 가져오기 작업이 런타임에 수행되기 때문입니다.

+
더 쉽게 검색하려면 검색어에 필터를 사용할 수 있습니다.  필터는 대소문자를 구분하며, 공백이 없는 Perl 표현식입니다.  기본 검색 문자열은 다음과 같습니다. `.` *.  다음 표는 Perl 검색 표현식의 몇 가지 예를 보여줍니다.

+
|===
| 이 표현은… | 검색 내용… 


| . | 줄바꿈 문자를 제외한 모든 문자. 


| .* | 모든 문자열.  이것이 기본값입니다. 


| 에이 | 문자 a. 


| 복근 | 현 ab. 


| a [수직 막대] b | 문자 a 또는 b. 


| 에이* | a라는 문자가 0개 이상 있습니다. 


| 아+ | a라는 문자의 하나 이상의 인스턴스. 


| 에이? | a라는 문자가 0개 또는 1개 있습니다. 


| 도끼} | 문자 a의 인스턴스가 정확히 x개입니다. 


| 도끼,} | 문자 a의 인스턴스가 최소 x개 있습니다. 


| a{x,y} | 문자 a의 인스턴스는 최소 x개, 최대 y개입니다. 


| \ | 특수문자를 이스케이프합니다. 
|===
+
게스트 파일 찾아보기 페이지에는 다른 모든 파일과 폴더 외에도 숨겨진 파일과 폴더가 모두 표시됩니다.

. 복원하려는 파일이나 폴더를 하나 이상 선택한 다음, *복원 위치 선택*을 선택합니다.
+
복원할 파일과 폴더는 선택한 파일 표에 나열됩니다.

. *복원 위치 선택* 페이지에서 다음을 지정합니다.
+
|===
| 옵션 | 설명 


| 경로로 복원 | 선택한 파일이 복원될 게스트의 UNC 공유 경로를 입력합니다.  IPv4 주소 예: `\\10.60.136.65\c$` IPv6 주소 예: `\\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore` 


| 원본 파일이 존재하는 경우  a| 
복원할 파일이나 폴더가 복원 대상에 이미 있는 경우 수행할 작업을 선택합니다: 항상 덮어쓰기 또는 항상 건너뛰기.


NOTE: 폴더가 이미 존재하는 경우 폴더의 내용이 기존 폴더와 병합됩니다.



| 성공적인 복원 후 게스트 세션 연결 끊기 | 복원 작업이 완료되면 게스트 파일 복원 세션을 삭제하려면 이 옵션을 선택하세요. 
|===
. *복원*을 선택하세요.
+
대시보드 작업 모니터에서 복원 작업의 진행 상황을 볼 수도 있고, 이메일 알림을 기다릴 수도 있습니다.  이메일 알림이 전송되는 데 걸리는 시간은 복원 작업이 완료되는 데 걸리는 시간에 따라 달라집니다.

+
알림 이메일에는 복원 작업의 출력이 포함된 첨부 파일이 포함되어 있습니다.  복구 작업이 실패하면 첨부 파일을 열어 추가 정보를 확인하세요.


