---
sidebar: sidebar 
permalink: scpivs44_post_deployment_required_operations_and_issues.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere 배포한 후 설치를 완료해야 합니다. 
---
= 배치 후 필요한 작업 및 문제
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphere 배포한 후 설치를 완료해야 합니다.



[[required-operations-after-deployment]]
== 배치 후 필요한 작업

SnapCenter 처음 사용하는 경우 데이터 보호 작업을 수행하기 전에 SnapCenter 에 스토리지 VM을 추가해야 합니다.  스토리지 VM을 추가할 때 관리 LIF를 지정합니다.  클러스터를 추가하고 클러스터 관리 LIF를 지정할 수도 있습니다.  저장소 추가에 대한 정보는 다음을 참조하세요.link:scpivs44_add_storage_01.html["저장공간 추가"^] .



[[deployment-issues-you-might-encounter]]
== 발생할 수 있는 배포 문제

* 가상 어플라이언스를 배포한 후 다음과 같은 경우에는 대시보드의 *백업 작업* 탭이 로드되지 않을 수 있습니다.
+
** IPv4 주소를 실행 중이고 SnapCenter VMware vSphere 호스트에 대한 두 개의 IP 주소가 있습니다.  결과적으로 작업 요청은 SnapCenter 서버에서 인식할 수 없는 IP 주소로 전송됩니다.  이 문제를 방지하려면 다음과 같이 사용하려는 IP 주소를 추가하세요.
+
... SnapCenter Plug-in for VMware vSphere 배포된 위치로 이동합니다. `/opt/netapp/scvservice/standalone_aegis/etc`
... network-interface.properties 파일을 엽니다.
... 에서 `network.interface=10.10.10.10` 필드에 사용하려는 IP 주소를 추가하세요.


** NIC가 두 개 있습니다.


* SnapCenter Plug-in for VMware vSphere 배포한 후에도 SnapCenter Plug-in for VMware vSphere 의 vCenter에 있는 MOB 항목에 여전히 이전 버전 번호가 표시될 수 있습니다.  이는 vCenter에서 다른 작업이 실행 중일 때 발생할 수 있습니다. vCenter는 결국 항목을 업데이트합니다.


이러한 문제를 해결하려면 다음을 수행하세요.

. 브라우저 캐시를 지운 다음 GUI가 제대로 작동하는지 확인하세요.
+
문제가 지속되면 VMware vSphere 클라이언트 서비스를 다시 시작하세요.

. vCenter에 로그인한 다음 도구 모음에서 *메뉴*를 선택하고 * SnapCenter Plug-in for VMware vSphere*을 선택합니다.




[[manage-authentication-errors]]
== 인증 오류 관리

관리자 자격 증명을 사용하지 않으면 SnapCenter Plug-in for VMware vSphere 배포하거나 마이그레이션한 후 인증 오류가 발생할 수 있습니다.  인증 오류가 발생하면 서비스를 다시 시작해야 합니다.

.단계
. 다음 형식을 사용하여 SnapCenter Plug-in for VMware vSphere 에 로그온합니다. `\https://<appliance-IP-address>:8080` . 관리자 사용자 이름, 비밀번호 및 MFA 토큰 세부 정보를 사용하여 로그인하세요. MFA 토큰은 유지 관리 콘솔에서 생성할 수 있습니다.
. 서비스를 다시 시작합니다.




[[register-snapcenter-plug-in-for-vmware-vsphere-with-snapcenter-server]]
== SnapCenter 서버 SnapCenter Plug-in for VMware vSphere 등록

SnapCenter 에서 VMDK 기반 애플리케이션 워크플로(가상화된 데이터베이스 및 파일 시스템을 위한 애플리케이션 기반 보호 워크플로)를 수행하려면 SnapCenter 서버에 SnapCenter Plug-in for VMware vSphere 등록해야 합니다.

.시작하기 전에
* SnapCenter Server 4.2 이상을 실행해야 합니다.
* SnapCenter Plug-in for VMware vSphere 배포하고 활성화해야 합니다.


.이 작업에 관하여
* SnapCenter GUI를 사용하여 "vsphere" 유형 호스트를 추가하여 SnapCenter Server에 SnapCenter Plug-in for VMware vSphere 등록합니다.
+
포트 8144는 SnapCenter Plug-in for VMware vSphere 내 통신을 위해 미리 정의되어 있습니다.

+
동일한 SnapCenter 서버에서 SnapCenter Plug-in for VMware vSphere 의 여러 인스턴스를 등록하여 VM에서 애플리케이션 기반 데이터 보호 작업을 지원할 수 있습니다.  여러 SnapCenter 서버에 동일한 SnapCenter Plug-in for VMware vSphere 등록할 수 없습니다.

* 연결 모드의 vCenter의 경우 각 vCenter에 대해 SnapCenter Plug-in for VMware vSphere 등록해야 합니다.


.단계
. SnapCenter GUI 왼쪽 탐색 창에서 *호스트*를 선택합니다.
. 상단에서 *관리되는 호스트* 탭이 선택되어 있는지 확인한 다음, 가상 어플라이언스 호스트 이름을 찾아 SnapCenter 서버에서 확인되는지 확인합니다.
. 마법사를 시작하려면 *추가*를 선택하세요.
. *호스트 추가* 대화 상자에서 다음 표에 나열된 대로 SnapCenter 서버에 추가할 호스트를 지정합니다.
+
|===
| 이 분야에서는… | 이렇게 하세요… 


| 호스트 유형 | 호스트 유형으로 *vSphere*를 선택합니다. 


| 호스트 이름 | 가상 어플라이언스의 IP 주소를 확인하세요. 


| 신임장 | 배포 중에 제공된 SnapCenter Plug-in for VMware vSphere 의 사용자 이름과 비밀번호를 입력하세요. 
|===
. *제출*을 선택하세요.
+
VM 호스트가 성공적으로 추가되면 관리 호스트 탭에 표시됩니다.

. 왼쪽 탐색 창에서 *설정*을 선택한 다음 *자격 증명* 탭을 선택하고 *추가*를 선택하여 가상 어플라이언스에 대한 자격 증명을 추가합니다.
. SnapCenter Plug-in for VMware vSphere 배포 중에 지정된 자격 증명 정보를 제공합니다.
+

NOTE: 인증 필드에서는 Linux를 선택해야 합니다.



.당신이 완료한 후
SnapCenter Plug-in for VMware vSphere 자격 증명이 수정된 경우 SnapCenter 관리 호스트 페이지를 사용하여 SnapCenter 서버에서 등록을 업데이트해야 합니다.
